export type Enhetstype =
  | "AAREG"
  | "ALS"
  | "ARK"
  | "DIR"
  | "DOKSENTER"
  | "EKSTERN"
  | "FPY"
  | "FYLKE"
  | "HELFO"
  | "HMS"
  | "INNKREV"
  | "INTRO"
  | "IT"
  | "KLAGE"
  | "KO"
  | "KONTAKT"
  | "KONTROLL"
  | "LOKAL"
  | "OKONOMI"
  | "OPPFUTLAND"
  | "RIKSREV"
  | "ROBOT"
  | "ROL"
  | "TILLIT"
  | "TILTAK"
  | "UKJENT"
  | "UTLAND"
  | "YTA";

export interface Enhet {
  aktiveringsdato: string;
  antallRessurser: number;
  enhetId: number;
  enhetNr: string;
  kanalstrategi: string;
  navn: string;
  nedleggelsesdato: string;
  oppgavebehandler: boolean;
  orgNivaa: string;
  orgNrTilKommunaltNavKontor: string;
  organisasjonsnummer: string;
  sosialeTjenester: string;
  status: string;
  type: Enhetstype;
  underAvviklingDato: string;
  underEtableringDato: string;
  versjon: number;
}
