import {WorkflowDispatchEvent} from "@octokit/webhooks-types";

const defaultGithubWorkflowDispatchEvent = {
  "enterprise": {
    "avatar_url": "https://avatars.githubusercontent.com/b/999999?v=4",
    "created_at": "2019-06-26T11:17:54Z",
    "description": "",
    "html_url": "https://github.com/enterprises/hsimpsonorg",
    "id": 987654321,
    "name": "HSimpson",
    "node_id": "ASDFASDJK3ASD3ASD5DFSG=",
    "slug": "hsimpson",
    "updated_at": "2021-07-08T05:16:12Z",
    "website_url": "https://hsimpson.com"
  },
  "inputs": {
    "formJsonFileTitle": "",
    "formDescription": "",
    "encodedFormJson": "",
    "encodedTranslationJson": "",
    "monorepoGitHash": ""
  },
  "organization": {
    "avatar_url": "https://avatars.githubusercontent.com/u/11848947?v=4",
    "description": "Arbeids- og velferdsdirektoratet - The Norwegian Labour and Welfare Directorate",
    "events_url": "https://api.github.com/orgs/hsimpsonorg/events",
    "hooks_url": "https://api.github.com/orgs/hsimpsonorg/hooks",
    "id": 987654321,
    "issues_url": "https://api.github.com/orgs/hsimpsonorg/issues",
    "login": "hsimpson",
    "members_url": "https://api.github.com/orgs/hsimpsonorg/members{/member}",
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjExODQ4OTQ3",
    "public_members_url": "https://api.github.com/orgs/hsimpsonorg/public_members{/member}",
    "repos_url": "https://api.github.com/orgs/hsimpsonorg/repos",
    "url": "https://api.github.com/orgs/hsimpsonorg"
  },
  "ref": "refs/heads/main",
  "repository": {
    "archive_url": "https://api.github.com/repos/hsimpson/funny-repo/{archive_format}{/ref}",
    "archived": false,
    "assignees_url": "https://api.github.com/repos/hsimpson/funny-repo/assignees{/user}",
    "blobs_url": "https://api.github.com/repos/hsimpson/funny-repo/git/blobs{/sha}",
    "branches_url": "https://api.github.com/repos/hsimpson/funny-repo/branches{/branch}",
    "clone_url": "https://github.com/hsimpson/funny-repo.git",
    "collaborators_url": "https://api.github.com/repos/hsimpson/funny-repo/collaborators{/collaborator}",
    "comments_url": "https://api.github.com/repos/hsimpson/funny-repo/comments{/number}",
    "commits_url": "https://api.github.com/repos/hsimpson/funny-repo/commits{/sha}",
    "compare_url": "https://api.github.com/repos/hsimpson/funny-repo/compare/{base}...{head}",
    "contents_url": "https://api.github.com/repos/hsimpson/funny-repo/contents/{+path}",
    "contributors_url": "https://api.github.com/repos/hsimpson/funny-repo/contributors",
    "created_at": "2021-05-11T11:26:17Z",
    "default_branch": "main",
    "deployments_url": "https://api.github.com/repos/hsimpson/funny-repo/deployments",
    "description": null,
    "disabled": false,
    "downloads_url": "https://api.github.com/repos/hsimpson/funny-repo/downloads",
    "events_url": "https://api.github.com/repos/hsimpson/funny-repo/events",
    "fork": false,
    "forks": 0,
    "forks_count": 0,
    "forks_url": "https://api.github.com/repos/hsimpson/funny-repo/forks",
    "full_name": "hsimpson/funny-repo",
    "git_commits_url": "https://api.github.com/repos/hsimpson/funny-repo/git/commits{/sha}",
    "git_refs_url": "https://api.github.com/repos/hsimpson/funny-repo/git/refs{/sha}",
    "git_tags_url": "https://api.github.com/repos/hsimpson/funny-repo/git/tags{/sha}",
    "git_url": "git://github.com/hsimpson/funny-repo.git",
    "has_downloads": true,
    "has_issues": true,
    "has_pages": false,
    "has_projects": true,
    "has_wiki": true,
    "homepage": null,
    "hooks_url": "https://api.github.com/repos/hsimpson/funny-repo/hooks",
    "html_url": "https://github.com/hsimpson/funny-repo",
    "id": 987654321,
    "issue_comment_url": "https://api.github.com/repos/hsimpson/funny-repo/issues/comments{/number}",
    "issue_events_url": "https://api.github.com/repos/hsimpson/funny-repo/issues/events{/number}",
    "issues_url": "https://api.github.com/repos/hsimpson/funny-repo/issues{/number}",
    "keys_url": "https://api.github.com/repos/hsimpson/funny-repo/keys{/key_id}",
    "labels_url": "https://api.github.com/repos/hsimpson/funny-repo/labels{/name}",
    "language": "JavaScript",
    "languages_url": "https://api.github.com/repos/hsimpson/funny-repo/languages",
    "license": null,
    "merges_url": "https://api.github.com/repos/hsimpson/funny-repo/merges",
    "milestones_url": "https://api.github.com/repos/hsimpson/funny-repo/milestones{/number}",
    "mirror_url": null,
    "name": "skjemapublisering-monorepo-poc",
    "node_id": "MDEwOlJlcG9zaXRvcnkzNjYzNTcyMjc=",
    "notifications_url": "https://api.github.com/repos/hsimpson/funny-repo/notifications{?since,all,participating}",
    "open_issues": 0,
    "open_issues_count": 0,
    "owner": {
      "avatar_url": "https://avatars.githubusercontent.com/u/11848947?v=4",
      "events_url": "https://api.github.com/users/hsimpsonorg/events{/privacy}",
      "followers_url": "https://api.github.com/users/hsimpsonorg/followers",
      "following_url": "https://api.github.com/users/hsimpsonorg/following{/other_user}",
      "gists_url": "https://api.github.com/users/hsimpsonorg/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/hsimpsonorg",
      "id": 987654321,
      "login": "hsimpsonorg",
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjExODQ4OTQ3",
      "organizations_url": "https://api.github.com/users/hsimpsonorg/orgs",
      "received_events_url": "https://api.github.com/users/hsimpsonorg/received_events",
      "repos_url": "https://api.github.com/users/hsimpsonorg/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/hsimpsonorg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hsimpsonorg/subscriptions",
      "type": "Organization",
      "url": "https://api.github.com/users/hsimpsonorg"
    },
    "private": false,
    "pulls_url": "https://api.github.com/repos/hsimpson/funny-repo/pulls{/number}",
    "pushed_at": "2021-08-23T08:36:51Z",
    "releases_url": "https://api.github.com/repos/hsimpson/funny-repo/releases{/id}",
    "size": 164,
    "ssh_url": "git@github.com:hsimpson/funny-repo.git",
    "stargazers_count": 0,
    "stargazers_url": "https://api.github.com/repos/hsimpson/funny-repo/stargazers",
    "statuses_url": "https://api.github.com/repos/hsimpson/funny-repo/statuses/{sha}",
    "subscribers_url": "https://api.github.com/repos/hsimpson/funny-repo/subscribers",
    "subscription_url": "https://api.github.com/repos/hsimpson/funny-repo/subscription",
    "svn_url": "https://github.com/hsimpson/funny-repo",
    "tags_url": "https://api.github.com/repos/hsimpson/funny-repo/tags",
    "teams_url": "https://api.github.com/repos/hsimpson/funny-repo/teams",
    "trees_url": "https://api.github.com/repos/hsimpson/funny-repo/git/trees{/sha}",
    "updated_at": "2021-08-23T08:36:53Z",
    "url": "https://api.github.com/repos/hsimpson/funny-repo",
    "watchers": 0,
    "watchers_count": 0
  },
  "sender": {
    "avatar_url": "https://avatars.githubusercontent.com/u/900509?v=4",
    "events_url": "https://api.github.com/users/hsimpson/events{/privacy}",
    "followers_url": "https://api.github.com/users/hsimpson/followers",
    "following_url": "https://api.github.com/users/hsimpson/following{/other_user}",
    "gists_url": "https://api.github.com/users/hsimpson/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/hsimpson",
    "id": 987654321,
    "login": "hsimpson",
    "node_id": "MDQ6VXNlcjkwMDUwOQ==",
    "organizations_url": "https://api.github.com/users/hsimpson/orgs",
    "received_events_url": "https://api.github.com/users/hsimpson/received_events",
    "repos_url": "https://api.github.com/users/hsimpson/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/hsimpson/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/hsimpson/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/hsimpson"
  },
  "workflow": ".github/workflows/test.yaml"
};

const workflowDispatchEventWithInputs = (inputs: { [key: string]: string }) => ({
  ...defaultGithubWorkflowDispatchEvent,
  inputs: {
    ...defaultGithubWorkflowDispatchEvent.inputs,
    ...inputs,
  }
} as WorkflowDispatchEvent)

export {workflowDispatchEventWithInputs};
export default defaultGithubWorkflowDispatchEvent as WorkflowDispatchEvent;
