apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: alert-skjemautfylling
  namespace: skjemadigitalisering
  labels:
    team: skjemadigitalisering
spec:
  receivers: # receivers for all alerts below
    slack:
      channel: '#skjemautfylling-feil-prod'
      prependText: '<!here> | ' # this text will be prepended to the Slack alert title
  alerts:
    - alert: applikasjon nede
      expr: 'sum(up{app="skjemautfylling", namespace="skjemadigitalisering"}) < 2'
      for: 1m
      description: "App {{ $labels.app }} er nede i namespace skjemadigitalisering"
      action: "Sjekk https://prometheus.prod-gcp.nais.io/alerts for detaljert info. Bruk kubectl i --namespace skjemadigitalisering for å finne ut hva som er feil i prod-gcp"
    - alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="skjemautfylling",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="skjemautfylling"}[3m]))) > 10
      for: 3m
      action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye feil. Read app logs at logs.adeo.no for application:skjemautfylling AND cluster:prod-gcp."
    - alert: nav.no/fyllut unavailable
      expr: 'kube_deployment_status_replicas_unavailable{deployment="skjemautfylling"} > 0'
      for: 2m
      action: Read app logs at logs.adeo.no for application:skjemautfylling AND cluster:prod-gcp.  Read Application events (kubectl describe deployment --namespace=skjemadigitalisering skjemautfylling)
      sla: respond within 1h, during office hours
      severity: danger
