---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: skjemautfylling
  namespace: skjemadigitalisering
  labels:
    team: skjemadigitalisering
spec:
  image: {{image}}
  team: skjemadigitalisering
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /fyllut/internal/isAlive
    initialDelay: 10
  readiness:
    path: /fyllut/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  accessPolicy:
    outbound:
      external:
        - host: {{dekorator-host}}
  env:
    - name: DECORATOR_URL
      value: https://{{dekorator-host}}/
