---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: skjemautfylling
  namespace: skjemadigitalisering
  labels:
    team: skjemadigitalisering
spec:
  image: {{image}}:{{version}}
  team: skjemadigitalisering
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /soknader/internal/isAlive
    initialDelay: 10
  readiness:
    path: /soknader/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: {{baseurl}}/internal/metrics
  vault:
    enabled: true
  replicas:
    min: 2
    max: 4
  webproxy: true
  resources:
    limits:
      cpu: '3'
      memory: 768Mi
    requests:
      memory: 512Mi
  env:
    -   name: DECORATOR_URL
        value: {{decoratorurl}}
