apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "self-hosted-runner"
  namespace: "skjemadigitalisering"
  labels:
    "team": "skjemadigitalisering"
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  accessPolicy:
    outbound:
      external:
        - host: skjemabygging-formio.dev.intern.nav.no
        - host: api.github.com
        - host: pipelines.actions.githubusercontent.com
        - host: github.com
  env:
    - name: ENVOY_ADMIN_API
      value: http://127.0.0.1:15000
    - name: ISTIO_QUIT_API
      value: http://127.0.0.1:15020
    - name: GITHUB_REPO
      value: "navikt/skjemabygging-formio"
    - name: GITHUB_PAT
      value: {{ githubPat }}
