const FILE_ACCEPT = '.pdf,.jpeg,.jpg,.docx,.doc,.odt,.rtf,.txt,.png,.tiff,.tif,.bmp,.gif';
const MAX_SIZE_ATTACHMENT_FILE_BYTES = 50 * 1024 * 1024; // 50 MB
const MAX_SIZE_ATTACHMENT_FILE_TEXT = '50 MB';
const MAX_TOTAL_SIZE_ATTACHMENT_FILES_BYTES = 50 * 1024 * 1024; // 50 MB
const MAX_TOTAL_SIZE_ATTACHMENT_FILES_TEXT = '50 MB';

export {
  FILE_ACCEPT,
  MAX_SIZE_ATTACHMENT_FILE_BYTES,
  MAX_SIZE_ATTACHMENT_FILE_TEXT,
  MAX_TOTAL_SIZE_ATTACHMENT_FILES_BYTES,
  MAX_TOTAL_SIZE_ATTACHMENT_FILES_TEXT,
};
