export const utenlandskAdresseSchema = (keyPostfix = "") => ({
  legend: "Utenlandsk kontaktadresse",
  key: "navSkjemagruppeUtland",
  type: "navSkjemagruppe",
  label: "Utenlandsk kontaktadresse",
  input: false,
  tableView: false,
  conditional: {
    show: true,
    when: "borDuINorge",
    eq: "nei",
  },
  components: [
    {
      label: "C/O",
      fieldSize: "input--xxl",
      validateOn: "blur",
      key: "utlandCoSoker",
      type: "textfield",
      input: true,
      dataGridLabel: true,
      tableView: true,
    },
    {
      label: "Gatenavn og husnummer, evt. postboks",
      fieldSize: "input--xxl",
      key: "utlandVegadresseOgHusnummerSoker",
      type: "textfield",
      input: true,
      dataGridLabel: true,
      tableView: true,
      autocomplete: "street-address",
      validateOn: "blur",
      validate: {
        required: true,
      },
    },
    {
      label: "Bygning",
      fieldSize: "input--xxl",
      validateOn: "blur",
      key: "utlandBygningSoker",
      type: "textfield",
      input: true,
      dataGridLabel: true,
      tableView: true,
    },
    {
      label: "Postkode",
      fieldSize: "input--s",
      validateOn: "blur",
      key: "utlandPostkodeSoker",
      type: "textfield",
      input: true,
      dataGridLabel: true,
      tableView: true,
    },
    {
      label: "By / stedsnavn",
      fieldSize: "input--xxl",
      validateOn: "blur",
      key: "utlandByStedSoker",
      type: "textfield",
      input: true,
      dataGridLabel: true,
      tableView: true,
    },
    {
      label: "Region",
      fieldSize: "input--xxl",
      validateOn: "blur",
      key: "utlandRegionSoker",
      type: "textfield",
      input: true,
      dataGridLabel: true,
      tableView: true,
    },
    {
      label: "Land",
      fieldSize: "input--xxl",
      key: "utlandLandSoker",
      type: "textfield",
      input: true,
      dataGridLabel: true,
      tableView: true,
      autocomplete: "country-name",
      validateOn: "blur",
      validate: {
        required: true,
      },
    },
  ],
});
