const common = {
  yes: 'Ja',
  no: 'Nei',
  optional: 'valgfritt',
  opensInNewTab: '(åpnes i ny fane)',
  january: 'Januar',
  february: 'Februar',
  march: 'Mars',
  april: 'April',
  may: 'Mai',
  june: 'Juni',
  july: 'Juli',
  august: 'August',
  september: 'September',
  october: 'Oktober',
  november: 'November',
  december: 'Desember',
  month: 'Måned',
  day: 'Dag',
  year: 'År',
};
export default common;
