export const grensesnitt = {
  //Grensesnitt / navigering
  navigation: {
    previous: 'Forrige steg',
    next: 'Neste steg',
    saveAndContinue: 'Lagre og fortsett',
    cancelAndDelete: 'Avbryt og slett',
    saveDraft: 'Lagre utkast og fortsett senere',
    uploadID: 'Opplasting av ID',
    sendToNav: 'Send til Nav',
    instructions: 'Instruksjoner for innsending',
    exit: 'Avslutt',
    summaryPageError: 'Du må fullføre utfyllingen før du kan fortsette',
  },
  mostRecentSave: 'Sist lagret',
  emptySubmissionError: 'Kan ikke fortsette. Innsendingen er tom.',
  languageSelector: {
    ariaLabel: 'Velg språk',
  },
  downloadApplication: 'Last ned skjema',
  confirmSavePrompt: {
    title: 'Lagre utkast og fortsett senere?',
    body: 'Skjemaet lagres som et utkast på Min Side slik at du kan fullføre senere. Skjemaet vil være tilgjengelig til {{date}}.',
    confirm: 'Ja, lagre og fortsett senere',
    cancel: 'Nei, fortsett utfylling',
  },
  confirmDeletePrompt: {
    title: 'Avbryt og slett utkast?',
    body: 'Alle opplysningene du har fylt ut vil bli slettet.',
    confirm: 'Ja, avbryt og slett utkast',
    cancel: 'Nei, fortsett utfylling',
  },
  confirmDiscardPrompt: {
    title: 'Avbryt og slett?',
    body: 'Alle opplysningene du har fylt ut vil bli slettet. Hvis du ønsker å fortsette utfyllingen senere kan du la nettleservinduet stå åpent til neste gang.',
    confirm: 'Ja, avbryt og slett',
    cancel: 'Nei, fortsett utfylling',
  },
  confirmCancelPrompt: {
    title: 'Avslutt?',
    body: 'Har du lastet ned og skrevet ut skjemaet?',
    confirm: 'Ja, avslutt',
    cancel: 'Nei',
  },
  formSummaryUtils: {
    payAttentionTo: 'Vær oppmerksom på',
  },
  introPage: {
    title: 'Introduksjon',
    sendDigital: 'Logg inn og send digitalt',
    sendDigitalLoggedIn: 'Send digitalt',
    sendDigitalDescription: 'Det er enklest og raskest å søke digitalt.',
    sendDigitalNoLogin: 'Send digitalt uten å logge inn',
    sendDigitalNoLoginDescription: 'Du må laste opp gyldig legitimasjon før du kan begynne å fylle ut.',
    sendOnPaper: 'Send i posten',
    sendOnPaperDescription: 'Du fyller ut søknaden før du skriver den ut. Du trenger ikke å logge inn.',
    noLogin: 'Kan ikke logge inn',
    noLoginDescription: 'Velg mellom å sende i posten eller å sende digitalt uten å logge inn.',
    changeSubmissionMethod: 'Send inn på en annen måte',
  },
  summaryPage: {
    edit: 'Endre svar',
    editAnswers: 'Fortsett utfylling',
  },
  stepper: {
    step: 'Steg {activeStep} av {totalSteps}',
    showAllSteps: 'Vis alle steg',
    hideAllSteps: 'Skjul alle steg',
  },
  navSelect: {
    defaultLabel: 'Nedtrekksmeny',
    numberOfAvailableOptions: '{{count}} valg tilgjengelig',
    labelWithFocusSelected: '{{label}} har fokus, er valgt.',
    labelWithFocusNotSelected: '{{label}} har fokus, er ikke valgt.',
    noOptionSelected: 'Ingen verdi er valgt.',
    optionSelected: '{{label}} er valgt',
    optionDeselected: '{{label}} er nå fjernet.',
    optionDisabled: '{{label}} er deaktivert, og kan ikke velges.',
    inputHasFocus: '{{label}} har fokus.',
    onFilterSearchResult: 'for søkeordet {{inputValue}}.',
  },
  navTextarea: {
    counterLeft: 'tegn igjen',
    counterTooMuch: 'tegn for mye',
  },
};
