name: Deploy alerts to NAIS
on:
  push:
    branches:
      - master
      - auto-deploy-alerts
    paths:
      - '.nais/alerts-prod-gcp.yaml'
      - '.github/workflows/alert-deploy.yaml'
jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts-prod-gcp.yaml
