import { KeyBasedFormsApiTranslation } from './index';

const introPage: KeyBasedFormsApiTranslation[] = [
  {
    key: 'introPage.guidePanel.hi',
    nb: 'Hei!',
    nn: 'Hei!',
    en: 'Hi!',
  },
  {
    key: 'introPage.guidePanel.hiPersonalized',
    nb: 'Hei, {{name}}!',
    nn: 'Hei, {{name}}!',
    en: 'Hi, {{name}}!',
  },
  {
    key: 'introPage.scope.title.alt1',
    nb: 'Her kan du søke om',
    nn: 'Her kan du søkja om',
    en: 'You may apply for',
  },
  {
    key: 'introPage.scope.title.alt2',
    nb: 'Her kan du melde om',
    nn: 'Her kan du melda om',
    en: 'You may report',
  },
  {
    key: 'introPage.scope.title.alt3',
    nb: 'Her kan du',
    nn: 'Her kan du',
    en: 'You may',
  },
  {
    key: 'introPage.outOfScope.title.alt1',
    nb: 'Dette kan du ikke søke om her',
    nn: 'Dette kan du ikkje søkja om her',
    en: 'You may not apply for',
  },
  {
    key: 'introPage.outOfScope.title.alt2',
    nb: 'Dette kan du ikke gjøre her',
    nn: 'Dette kan du ikkje gjera her',
    en: 'You may not',
  },
  {
    key: 'introPage.outOfScope.title.alt3',
    nb: 'Her kan du ikke',
    nn: 'Her kan du ikkje',
    en: 'You may not',
  },
  {
    key: 'introPage.prerequisites.title.alt1',
    nb: 'Før du søker',
    nn: 'Før du søkjer',
    en: 'Before you apply',
  },
  {
    key: 'introPage.prerequisites.title.alt2',
    nb: 'Før du svarer',
    nn: 'Før du svarer',
    en: 'Before you reply',
  },
  {
    key: 'introPage.prerequisites.title.alt3',
    nb: 'Før du fyller ut',
    nn: 'Før du fyller ut',
    en: 'Before you fill in the form',
  },
  {
    key: 'introPage.beAwareOf.title',
    nb: 'Vær klar over',
    nn: 'Vær klar over',
    en: 'Be aware of',
  },
  {
    key: 'introPage.beAwareOf.mandatoryFields',
    nb: 'De fleste feltene i skjemaet er obligatoriske å fylle ut. Felt som ikke er obligatoriske er merket med: (valgfritt).',
    nn: 'Dei fleste felta i skjemaet er obligatoriske å fylla ut. Felt som ikkje er obligatoriske er merkt med: (valfritt).',
    en: 'Most fields in the form are mandatory to fill out. Fields that are not mandatory are marked with: (optional).',
  },
  {
    key: 'introPage.beAwareOf.useOfPublicComputers',
    nb: 'Bruk av offentlig PC: Hvis du fyller ut skjemaet på en offentlig PC, for eksempel på et bibliotek, er det viktig at du lukker nettleseren når du er ferdig. Dette vil forhindre at uvedkommende får tak i opplysningene du har fylt ut i skjemaet.',
    nn: 'Bruk av offentleg PC: Om du fyller ut skjemaet på ein offentleg PC, til dømes på eit bibliotek, er det viktig at du lukkar nettlesaren når du er ferdig. Dette vil forhindra at uvedkommande får tak i opplysningane du har fylt ut i skjemaet.',
    en: 'Use of public computers: If you fill out the form on a public computer, for example at a library, it is important that you close the browser when you are finished. This will prevent unauthorized persons from accessing the information you have entered in the form.',
  },
  {
    key: 'introPage.beAwareOf.sendByMail',
    nb: 'Du må fylle ut skjemaet digitalt, og så sende det i posten. Etter utfylling må du laste ned det ferdig utfylte skjemaet som en PDF-fil, skrive det ut, signere og sende det i posten.',
    nn: 'Du må fylle ut skjemaet digitalt, og så sende det i posten. Etter utfylling må du laste ned det ferdig utfylte skjemaet som ein PDF-fil, skriva det ut, signera og senda det i posten.',
    en: 'You must complete the form digitally and then send it by mail. After filling it out, you must download the completed form as a PDF file, print it, sign it, and send it by mail.',
  },
  {
    key: 'introPage.beAwareOf.notSave',
    nb: 'Du kan ikke lagre skjemaet underveis. Informasjonen du fyller ut i skjemaet sendes ikke til Nav før du har fullført hele skjemaet og sendt det inn. Hvis du lukker vinduet eller nettleseren vil all informasjon du har fylt ut forsvinne.',
    nn: 'Du kan ikkje lagre skjemaet undervegs. Informasjonen du fyller ut i skjemaet blir ikkje sendt til Nav før du har fullført heile skjemaet og sendt det inn. Viss du lukkar vindauget eller nettlesaren vil all informasjon du har fylt ut forsvinne.',
    en: 'The form cannot be saved before you are finished. The information you fill in the form is not sent to Nav until you have completed the entire form and submitted it. If you close the window or browser, all the information you have entered will disappear.',
  },
  {
    key: 'introPage.beAwareOf.timeLimit',
    nb: 'Det er ingen tidsfrist på å fullføre utfyllingen, men hvis du lukker vinduet/fanen vil du miste alle opplysningene du har lagt inn. Opplysningene sendes ikke til Nav før du har fullført hele skjemaet og sendt det inn.',
    nn: 'Det er ingen tidsfrist på å fullføre utfyllinga, men om du lukkar vindauget eller fana vil du missa alle opplysningane du har lagt inn. Opplysningane blir ikkje sendt til Nav før du har fullført heile skjemaet og sendt det inn.',
    en: 'There is no deadline to complete the form, but if you close the window or tab, you will lose all the information you have entered. The information is not sent to Nav until you have completed the entire form and submitted it.',
  },
  {
    key: 'introPage.dataDisclosure.title.alt1',
    nb: 'Informasjon vi henter om deg',
    nn: 'Informasjon me hentar om deg',
    en: 'Information we collect about you',
  },
  {
    key: 'introPage.dataDisclosure.title.alt2',
    nb: 'Informasjon vi henter',
    nn: 'Informasjon me hentar',
    en: 'Information we collect',
  },
  {
    key: 'introPage.dataDisclosure.ingress',
    nb: 'I tillegg til den informasjonen du oppgir i skjemaet, henter vi:',
    nn: 'I tillegg til den informasjonen du oppgir i skjemaet, hentar me:',
    en: 'In addition to the information you provide, we collect:',
  },
  {
    key: 'introPage.dataDisclosure.nationalPopulationRegister',
    nb: 'Person- og adresseinformasjon fra Folkeregisteret',
    nn: 'Person- og adresseinformasjon frå Folkeregisteret',
    en: 'Personal and address information from the National Population Register',
  },
  {
    key: 'introPage.dataTreatment.title',
    nb: 'Hvordan vi behandler personopplysninger',
    nn: 'Korleis me behandlar personopplysningar',
    en: 'How we process personal data',
  },
  {
    key: 'introPage.dataStorage.title.digital',
    nb: 'Vi lagrer svar underveis',
    nn: 'Me lagrar svar undervegs',
    en: 'We save your answers',
  },
  {
    key: 'introPage.dataStorage.ingress.digital',
    nb: 'Vi lagrer et utkast av skjemaet automatisk hver gang du går til neste steg. Du finner utkastet på Min side. Nav kan ikke se informasjonen i utkastet. Du må trykke på “Send til Nav” for at Nav skal motta skjemaet/søknaden.',
    nn: 'Me lagrar eit utkast av skjemaet automatisk kvar gong du går til neste steg. Du finn utkastet på Mi side. Nav kan ikkje sjå informasjonen i utkastet. Du må trykkja på “Send til Nav” for at Nav skal få skjemaet/søknaden.',
    en: 'We automatically save a draft of the form each time you go to the next step. You can find the draft on My page. Nav cannot see the information in the draft. You must click “Send to Nav” for Nav to receive the form/application.',
  },
  {
    key: 'introPage.automaticProcessing.title',
    nb: 'Automatisk saksbehandling',
    nn: 'Automatisk saksbehandling',
    en: 'Automatic case processing',
  },
  {
    key: 'introPage.dataTreatment.readMore',
    nb: 'Du kan lese mer om <a href="https://www.nav.no/personvernerklaering" target="_blank" rel="noopener noreferrer">hvordan Nav behandler personopplysninger på nav.no (åpnes i ny fane).</a>',
    nn: 'Du kan lesa meir om <a href="https://www.nav.no/personvernerklaering" target="_blank" rel="noopener noreferrer">korleis Nav behandlar personopplysningar på nav.no (blir opna i ny fane).</a>',
    en: 'You can read more about <a href="https://www.nav.no/personvernerklaering/en" target="_blank" rel="noopener noreferrer">how Nav processes personal data on nav.no (opens in new tab).</a>',
  },
  {
    key: 'introPage.selfDeclaration.description.alt1',
    nb: 'Det er viktig at du gir oss riktige opplysninger slik at vi kan behandle henvendelsen din. <a href="https://www.nav.no/endringer" target="_blank" rel="noopener noreferrer">Les mer om viktigheten av å gi riktige opplysninger (åpnes i ny fane)</a>',
    nn: 'Det er viktig at du gir oss rette opplysningar slik at me kan behandla førespurnaden din. <a href="https://www.nav.no/endringer/nn" target="_blank" rel="noopener noreferrer">Les meir om viktigheita av å gi rette opplysningar (blir opna i ny fane)</a>',
    en: 'It is important that you provide us with correct information so that we can process your inquiry. <a href="https://www.nav.no/endringer/en" target="_blank" rel="noopener noreferrer">Read more about the importance of providing correct information (opens in new tab)</a>',
  },
  {
    key: 'introPage.selfDeclaration.description.alt2',
    nb: 'Det er viktig at du gir oss riktige opplysninger slik at vi kan behandle søknaden din. <a href="https://www.nav.no/endringer" target="_blank" rel="noopener noreferrer">Les mer om viktigheten av å gi riktige opplysninger (åpnes i ny fane)</a>',
    nn: 'Det er viktig at du gir oss rette opplysningar slik at me kan behandla søknaden din. <a href="https://www.nav.no/endringer/nn" target="_blank" rel="noopener noreferrer">Les meir om viktigheita av å gi rette opplysningar (blir opna i ny fane)</a>',
    en: 'It is important that you provide us with correct information so that we can process your application. <a href="https://www.nav.no/endringer/en" target="_blank" rel="noopener noreferrer">Read more about the importance of providing correct information (opens in new tab)</a>',
  },
  {
    key: 'introPage.selfDeclaration.description.alt3',
    nb: 'Det er viktig at du gir oss riktige opplysninger slik at vi kan behandle saken din. <a href="https://www.nav.no/endringer" target="_blank" rel="noopener noreferrer">Les mer om viktigheten av å gi riktige opplysninger (åpnes i ny fane)</a>',
    nn: 'Det er viktig at du gir oss rette opplysningar slik at me kan behandla saka di. <a href="https://www.nav.no/endringer/nn" target="_blank" rel="noopener noreferrer">Les meir om viktigheita av å gi rette opplysningar (blir opna i ny fane)</a>',
    en: 'It is important that you provide us with correct information so that we can process your case. <a href="https://www.nav.no/endringer/en" target="_blank" rel="noopener noreferrer">Read more about the importance of providing correct information (opens in new tab)</a>',
  },
  {
    key: 'introPage.selfDeclaration.description.alt4',
    nb: 'Det er viktig at du gir oss riktige opplysninger slik at vi kan behandle meldingen din. <a href="https://www.nav.no/endringer" target="_blank" rel="noopener noreferrer">Les mer om viktigheten av å gi riktige opplysninger (åpnes i ny fane)</a>',
    nn: 'Det er viktig at du gir oss rette opplysningar slik at me kan behandla meldinga di. <a href="https://www.nav.no/endringer/nn" target="_blank" rel="noopener noreferrer">Les mer om viktigheten av å gi riktige opplysninger (åpnes i ny fane)</a>',
    en: 'It is important that you provide us with correct information so that we can process your message. <a href="https://www.nav.no/endringer/en" target="_blank" rel="noopener noreferrer">Read more about the importance of providing correct information (opens in new tab)</a>',
  },
  {
    key: 'introPage.selfDeclaration.inputLabel',
    nb: 'Jeg bekrefter at jeg vil svare så riktig som jeg kan.',
    nn: 'Eg stadfestar at eg vil svara så rett som eg kan.',
    en: 'I confirm that I will answer as accurately as I can.',
  },
  {
    key: 'introPage.selfDeclaration.validationError',
    nb: 'Du må bekrefte at du vil svare så riktig som du kan.',
    nn: 'Du må stadfesta at du vil svara så rett som du kan.',
    en: 'You must confirm that you will answer as accurately as you can.',
  },
];

export default introPage;
