FROM node:24.14.0-alpine
ENV NODE_ENV=production
ARG git_sha

WORKDIR /app
COPY fyllut/dist build
COPY .deploy/fyllut-backend server

ENV GIT_SHA=${git_sha}
ENV MONOREPO_GIT_SHA=${git_sha}

WORKDIR server
CMD ["node", "dist/server.mjs"]

EXPOSE 8080
