FROM node:24.14.0-alpine
ENV NODE_ENV=production
ARG git_sha

WORKDIR /app
COPY form-spec-api/dist server
COPY form-spec-api/node_modules server/node_modules

ENV GIT_SHA=${git_sha}
WORKDIR server
CMD ["node", "server.mjs"]
