FROM node:18.16.1-alpine
ENV NODE_ENV production
ARG git_sha

WORKDIR /app
COPY bygger/dist build
COPY bygger-backend/dist server
COPY bygger-backend/node_modules server/node_modules

ENV GIT_SHA=${git_sha}
WORKDIR server
CMD ["node", "server.mjs"]
