import {Pdfgen} from "./pdfgen";

const originalForm = {
  "_id": "5f2812a61cd355000301f0d0",
  "type": "form",
  "tags": ["nav-skjema"],
  "owner": "5ee0eacc7665226ea32fd389",
  "components": [{
    "label": "HTML",
    "tag": "p",
    "className": "",
    "attrs": [{"attr": "", "value": ""}],
    "content": "Dette er en veiledningstekst <br>\n\nden går over to linjer",
    "refreshOnChange": false,
    "customClass": "",
    "hidden": false,
    "tableView": false,
    "modalEdit": false,
    "key": "html",
    "tags": [],
    "properties": {},
    "conditional": {"show": null, "when": null, "eq": "", "json": ""},
    "customConditional": "",
    "logic": [],
    "attributes": {},
    "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
    "type": "htmlelement",
    "input": false,
    "placeholder": "",
    "prefix": "",
    "suffix": "",
    "multiple": false,
    "defaultValue": null,
    "protected": false,
    "unique": false,
    "persistent": false,
    "clearOnHide": true,
    "refreshOn": "",
    "redrawOn": "",
    "labelPosition": "top",
    "description": "",
    "errorLabel": "",
    "tooltip": "",
    "hideLabel": false,
    "tabindex": "",
    "disabled": false,
    "autofocus": false,
    "dbIndex": false,
    "customDefaultValue": "",
    "calculateValue": "",
    "calculateServer": false,
    "widget": null,
    "validateOn": "change",
    "validate": {
      "required": false,
      "custom": "",
      "customPrivate": false,
      "strictDateValidation": false,
      "multiple": false,
      "unique": false
    },
    "allowCalculateOverride": false,
    "encrypted": false,
    "showCharCount": false,
    "showWordCount": false,
    "allowMultipleMasks": false,
    "id": "e5lcez"
  }, {
    "title": "Personalia",
    "theme": "default",
    "breadcrumb": "default",
    "breadcrumbClickable": true,
    "buttonSettings": {"previous": true, "cancel": true, "next": true},
    "tooltip": "",
    "customClass": "",
    "collapsible": false,
    "hidden": false,
    "disabled": false,
    "tableView": false,
    "modalEdit": false,
    "key": "personalia1",
    "tags": [],
    "properties": {},
    "customConditional": "",
    "conditional": {"json": "", "show": null, "when": null, "eq": ""},
    "nextPage": "",
    "logic": [],
    "attributes": {},
    "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
    "type": "panel",
    "label": "Panel",
    "tabindex": "",
    "input": false,
    "placeholder": "",
    "prefix": "",
    "suffix": "",
    "multiple": false,
    "defaultValue": null,
    "protected": false,
    "unique": false,
    "persistent": false,
    "clearOnHide": false,
    "refreshOn": "",
    "redrawOn": "",
    "labelPosition": "top",
    "description": "",
    "errorLabel": "",
    "hideLabel": false,
    "autofocus": false,
    "dbIndex": false,
    "customDefaultValue": "",
    "calculateValue": "",
    "calculateServer": false,
    "widget": null,
    "validateOn": "change",
    "validate": {
      "required": false,
      "custom": "",
      "customPrivate": false,
      "strictDateValidation": false,
      "multiple": false,
      "unique": false
    },
    "allowCalculateOverride": false,
    "encrypted": false,
    "showCharCount": false,
    "showWordCount": false,
    "allowMultipleMasks": false,
    "tree": false,
    "components": [{
      "label": "Personalia",
      "labelPosition": "top",
      "tooltip": "",
      "customClass": "",
      "hidden": false,
      "hideLabel": true,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "persistent": true,
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "validateOn": "change",
      "errorLabel": "",
      "key": "personalia",
      "tags": [],
      "properties": {},
      "conditional": {"show": null, "when": null, "eq": "", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "container",
      "input": true,
      "components": [{
        "label": "Fornavn",
        "type": "textfield",
        "key": "fornavn",
        "input": true,
        "placeholder": "Fornavn",
        "validate": {
          "required": true,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false,
          "multiple": false,
          "unique": false,
          "minLength": "",
          "maxLength": "",
          "pattern": ""
        },
        "prefix": "",
        "customClass": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": true,
        "hidden": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "tableView": true,
        "modalEdit": false,
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "calculateServer": false,
        "widget": {"type": "input"},
        "attributes": {},
        "validateOn": "change",
        "conditional": {"show": null, "when": null, "eq": ""},
        "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "properties": {},
        "allowMultipleMasks": false,
        "mask": false,
        "inputType": "text",
        "inputFormat": "plain",
        "inputMask": "",
        "spellcheck": true,
        "id": "e2i3kg5"
      }, {
        "label": "Etternavn",
        "type": "textfield",
        "key": "etternavn",
        "input": true,
        "placeholder": "Etternavn",
        "validate": {
          "required": true,
          "custom": "",
          "customPrivate": false,
          "strictDateValidation": false,
          "multiple": false,
          "unique": false,
          "minLength": "",
          "maxLength": "",
          "pattern": ""
        },
        "prefix": "",
        "customClass": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": true,
        "hidden": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "tableView": true,
        "modalEdit": false,
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "calculateServer": false,
        "widget": {"type": "input"},
        "attributes": {},
        "validateOn": "change",
        "conditional": {"show": null, "when": null, "eq": ""},
        "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "properties": {},
        "allowMultipleMasks": false,
        "mask": false,
        "inputType": "text",
        "inputFormat": "plain",
        "inputMask": "",
        "spellcheck": true,
        "id": "eu4ap99"
      }, {
        "key": "fodselsnummerDNummer",
        "type": "fnrfield",
        "input": true,
        "placeholder": "",
        "prefix": "",
        "customClass": "",
        "suffix": "",
        "multiple": false,
        "defaultValue": null,
        "protected": false,
        "unique": false,
        "persistent": true,
        "hidden": false,
        "clearOnHide": true,
        "refreshOn": "",
        "redrawOn": "",
        "tableView": true,
        "modalEdit": false,
        "label": "Fødselsnummer / D-nummer",
        "labelPosition": "top",
        "description": "",
        "errorLabel": "",
        "tooltip": "",
        "hideLabel": false,
        "tabindex": "",
        "disabled": false,
        "autofocus": false,
        "dbIndex": false,
        "customDefaultValue": "",
        "calculateValue": "",
        "calculateServer": false,
        "widget": {"type": "input"},
        "attributes": {},
        "validateOn": "blur",
        "validate": {
          "required": true,
          "custom": "valid = instance.validateFnr(input) ? true : 'Dette er ikke et gyldig fødselsnummer';",
          "customPrivate": false,
          "strictDateValidation": false,
          "multiple": false,
          "unique": false,
          "minLength": "",
          "maxLength": "",
          "pattern": ""
        },
        "conditional": {"show": null, "when": null, "eq": ""},
        "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
        "allowCalculateOverride": false,
        "encrypted": false,
        "showCharCount": false,
        "showWordCount": false,
        "properties": {},
        "allowMultipleMasks": false,
        "mask": false,
        "inputType": "text",
        "inputFormat": "plain",
        "inputMask": "999999 99999",
        "spellcheck": true,
        "id": "ecrz8yq"
      }],
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "refreshOn": "",
      "description": "",
      "tabindex": "",
      "autofocus": false,
      "widget": null,
      "allowCalculateOverride": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": true,
      "id": "ehnaj4mb"
    }, {
      "label": "Gateadresse",
      "labelPosition": "top",
      "placeholder": "Gateveien 1",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {"type": "input"},
      "inputMask": "",
      "allowMultipleMasks": false,
      "customClass": "",
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "showWordCount": false,
      "showCharCount": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "persistent": true,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": true,
        "pattern": "",
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "minLength": "",
        "maxLength": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "errorLabel": "",
      "key": "gateadresse",
      "tags": [],
      "properties": {},
      "customConditional": "",
      "conditional": {"json": "", "show": null, "when": null, "eq": ""},
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "textfield",
      "input": true,
      "refreshOn": "",
      "inputType": "text",
      "id": "es510b",
      "defaultValue": null
    }, {
      "label": "Postnummer",
      "labelPosition": "top",
      "placeholder": "1234",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {"type": "input"},
      "inputMask": "9999",
      "allowMultipleMasks": false,
      "customClass": "",
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "showWordCount": false,
      "showCharCount": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "persistent": true,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "blur",
      "validate": {
        "required": true,
        "pattern": "",
        "customMessage": "4 siffer",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "minLength": "",
        "maxLength": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "errorLabel": "",
      "key": "postnummer",
      "tags": [],
      "properties": {},
      "customConditional": "",
      "conditional": {"json": "", "show": null, "when": null, "eq": ""},
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "textfield",
      "input": true,
      "refreshOn": "",
      "inputType": "text",
      "id": "e0zzaog",
      "defaultValue": null
    }, {
      "label": "E-post",
      "labelPosition": "top",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {"type": "input"},
      "customClass": "",
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "persistent": true,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "pattern": "",
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "minLength": "",
        "maxLength": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "kickbox": {"enabled": false},
      "errorLabel": "",
      "key": "ePost",
      "tags": [],
      "properties": {},
      "conditional": {"show": null, "when": null, "eq": "", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "email",
      "input": true,
      "refreshOn": "",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "inputType": "email",
      "inputMask": "",
      "id": "e63h1cp",
      "defaultValue": null
    }],
    "id": "e9z73d"
  }, {
    "title": "Inntektsopplysninger",
    "theme": "default",
    "breadcrumb": "default",
    "breadcrumbClickable": true,
    "buttonSettings": {"previous": true, "cancel": true, "next": true},
    "tooltip": "",
    "customClass": "",
    "collapsible": false,
    "hidden": false,
    "disabled": false,
    "tableView": false,
    "modalEdit": false,
    "key": "inntektsopplysninger",
    "tags": [],
    "properties": {},
    "customConditional": "",
    "conditional": {"json": "", "show": null, "when": null, "eq": ""},
    "nextPage": "",
    "logic": [],
    "attributes": {},
    "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
    "type": "panel",
    "label": "Panel",
    "tabindex": "",
    "input": false,
    "placeholder": "",
    "prefix": "",
    "suffix": "",
    "multiple": false,
    "defaultValue": null,
    "protected": false,
    "unique": false,
    "persistent": false,
    "clearOnHide": false,
    "refreshOn": "",
    "redrawOn": "",
    "labelPosition": "top",
    "description": "",
    "errorLabel": "",
    "hideLabel": false,
    "autofocus": false,
    "dbIndex": false,
    "customDefaultValue": "",
    "calculateValue": "",
    "calculateServer": false,
    "widget": null,
    "validateOn": "change",
    "validate": {
      "required": false,
      "custom": "",
      "customPrivate": false,
      "strictDateValidation": false,
      "multiple": false,
      "unique": false
    },
    "allowCalculateOverride": false,
    "encrypted": false,
    "showCharCount": false,
    "showWordCount": false,
    "allowMultipleMasks": false,
    "tree": false,
    "components": [{
      "label": "Har du hatt lønnsinntekt?",
      "labelPosition": "top",
      "optionsLabelPosition": "right",
      "description": "",
      "tooltip": "",
      "customClass": "",
      "tabindex": "",
      "inline": true,
      "hidden": false,
      "hideLabel": false,
      "autofocus": false,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "values": [{"label": "Ja", "value": "ja", "shortcut": ""}, {"label": "Nei", "value": "nei", "shortcut": ""}],
      "dataType": "",
      "persistent": true,
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "errorLabel": "",
      "key": "harDuHattLonnsinntekt",
      "tags": [],
      "properties": {},
      "conditional": {"show": null, "when": null, "eq": "", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "radio",
      "input": true,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "unique": false,
      "refreshOn": "",
      "widget": null,
      "validateOn": "change",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "inputType": "radio",
      "fieldSet": false,
      "id": "es3j2ze",
      "defaultValue": ""
    }, {
      "label": "Inntekt",
      "labelPosition": "top",
      "placeholder": "Beløp i hele kroner",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {"type": "input"},
      "customClass": "",
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "multiple": false,
      "defaultValue": 0,
      "persistent": true,
      "currency": "NOK",
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "encrypted": false,
      "redrawOn": "data",
      "clearOnHide": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
        "min": "",
        "max": "",
        "step": "any",
        "integer": ""
      },
      "unique": false,
      "errorLabel": "",
      "key": "inntekt",
      "tags": [],
      "properties": {},
      "conditional": {"show": true, "when": "harDuHattLonnsinntekt", "eq": "ja", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "currency",
      "input": true,
      "delimiter": true,
      "refreshOn": "",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "id": "ewawt9q"
    }, {
      "label": "Har du hatt næringsinntekt?",
      "labelPosition": "top",
      "optionsLabelPosition": "right",
      "description": "",
      "tooltip": "",
      "customClass": "",
      "tabindex": "",
      "inline": true,
      "hidden": false,
      "hideLabel": false,
      "autofocus": false,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "values": [{"label": "Ja", "value": "ja", "shortcut": ""}, {"label": "Nei", "value": "nei", "shortcut": ""}],
      "dataType": "",
      "persistent": true,
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "errorLabel": "",
      "key": "harDuHattNaringsinntekt",
      "tags": [],
      "properties": {},
      "conditional": {"show": null, "when": null, "eq": "", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "radio",
      "input": true,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "unique": false,
      "refreshOn": "",
      "widget": null,
      "validateOn": "change",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "inputType": "radio",
      "fieldSet": false,
      "id": "eyqwi2p",
      "defaultValue": ""
    }, {
      "label": "Inntekt",
      "labelPosition": "top",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {"type": "input"},
      "customClass": "",
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "multiple": false,
      "defaultValue": 0,
      "persistent": true,
      "currency": "nok",
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "encrypted": false,
      "redrawOn": "data",
      "clearOnHide": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
        "min": "",
        "max": "",
        "step": "any",
        "integer": ""
      },
      "unique": false,
      "errorLabel": "",
      "key": "inntekt1",
      "tags": [],
      "properties": {},
      "conditional": {"show": true, "when": "harDuHattNaringsinntekt", "eq": "ja", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "currency",
      "input": true,
      "delimiter": true,
      "refreshOn": "",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "id": "emrf2v5"
    }, {
      "label": "Har du hatt valutainntekt?",
      "labelPosition": "top",
      "optionsLabelPosition": "right",
      "description": "",
      "tooltip": "",
      "customClass": "",
      "tabindex": "",
      "inline": true,
      "hidden": false,
      "hideLabel": false,
      "autofocus": false,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "values": [{"label": "Ja", "value": "ja", "shortcut": ""}, {"label": "Nei", "value": "nei", "shortcut": ""}],
      "dataType": "",
      "persistent": true,
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "errorLabel": "",
      "key": "harDuHattValutainntekt",
      "tags": [],
      "properties": {},
      "conditional": {"show": null, "when": null, "eq": "", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "radio",
      "input": true,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "unique": false,
      "refreshOn": "",
      "widget": null,
      "validateOn": "change",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "inputType": "radio",
      "fieldSet": false,
      "id": "eqnu0nl",
      "defaultValue": ""
    }, {
      "label": "Inntekt",
      "labelPosition": "top",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {"type": "input"},
      "customClass": "",
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "multiple": false,
      "defaultValue": 0,
      "persistent": true,
      "currency": "nok",
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
        "min": "",
        "max": "",
        "step": "any",
        "integer": ""
      },
      "unique": false,
      "errorLabel": "",
      "key": "inntekt2",
      "tags": [],
      "properties": {},
      "conditional": {"show": true, "when": "harDuHattValutainntekt", "eq": "ja", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "currency",
      "input": true,
      "delimiter": true,
      "refreshOn": "",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "id": "e6sscje"
    }, {
      "label": "Har du hatt andre inntekter?",
      "labelPosition": "top",
      "optionsLabelPosition": "right",
      "description": "",
      "tooltip": "",
      "customClass": "",
      "tabindex": "",
      "inline": true,
      "hidden": false,
      "hideLabel": false,
      "autofocus": false,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "values": [{"label": "Ja", "value": "ja", "shortcut": ""}, {"label": "Nei", "value": "nei", "shortcut": ""}],
      "dataType": "",
      "persistent": true,
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "errorLabel": "",
      "key": "harDuHattAndreInntekter",
      "tags": [],
      "properties": {},
      "conditional": {"show": null, "when": null, "eq": "", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "radio",
      "input": true,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "unique": false,
      "refreshOn": "",
      "widget": null,
      "validateOn": "change",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "inputType": "radio",
      "fieldSet": false,
      "id": "ekmagkp",
      "defaultValue": ""
    }, {
      "label": "Inntekt",
      "labelPosition": "top",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {"type": "input"},
      "customClass": "",
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "multiple": false,
      "defaultValue": 0,
      "persistent": true,
      "currency": "nok",
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "encrypted": false,
      "redrawOn": "data",
      "clearOnHide": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
        "min": "",
        "max": "",
        "step": "any",
        "integer": ""
      },
      "unique": false,
      "errorLabel": "",
      "key": "inntekt3",
      "tags": [],
      "properties": {},
      "conditional": {"show": true, "when": "harDuHattAndreInntekter", "eq": "ja", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "currency",
      "input": true,
      "delimiter": true,
      "refreshOn": "",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "id": "ei5wbp"
    }, {
      "label": "Sum",
      "labelPosition": "top",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {"type": "input"},
      "customClass": "",
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "multiple": false,
      "persistent": true,
      "currency": "NOK",
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "encrypted": false,
      "redrawOn": "data",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "value = data.inntekt + data.inntekt1 + data.inntekt2 + data.inntekt3;",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
        "min": "",
        "max": "",
        "step": "any",
        "integer": ""
      },
      "unique": false,
      "errorLabel": "",
      "key": "sum",
      "tags": [],
      "properties": {},
      "conditional": {"show": null, "when": null, "eq": "", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "currency",
      "input": true,
      "delimiter": true,
      "refreshOn": "",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "id": "e5cym5",
      "defaultValue": null
    }, {
      "label": "Tall",
      "labelPosition": "top",
      "placeholder": "Beløp i hele kroner",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {"type": "input"},
      "customClass": "",
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "multiple": false,
      "persistent": true,
      "delimiter": true,
      "requireDecimal": false,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "value = data.inntekt + data.inntekt1 + data.inntekt2 + data.inntekt3;",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "min": "",
        "max": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
        "step": "any",
        "integer": ""
      },
      "errorLabel": "",
      "key": "tall",
      "tags": [],
      "properties": {},
      "conditional": {"show": null, "when": null, "eq": "", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "number",
      "input": true,
      "unique": false,
      "refreshOn": "",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "id": "exkmmf8",
      "defaultValue": null
    }],
    "id": "edfcko9"
  }, {
    "title": "Summeringstest",
    "theme": "default",
    "breadcrumb": "default",
    "breadcrumbClickable": true,
    "buttonSettings": {"previous": true, "cancel": true, "next": true},
    "tooltip": "",
    "customClass": "",
    "collapsible": false,
    "hidden": false,
    "disabled": false,
    "tableView": false,
    "modalEdit": false,
    "key": "summeringstest",
    "tags": [],
    "properties": {},
    "customConditional": "",
    "conditional": {"json": "", "show": null, "when": null, "eq": ""},
    "nextPage": "",
    "logic": [],
    "attributes": {},
    "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
    "type": "panel",
    "label": "Panel",
    "tabindex": "",
    "input": false,
    "placeholder": "",
    "prefix": "",
    "suffix": "",
    "multiple": false,
    "defaultValue": null,
    "protected": false,
    "unique": false,
    "persistent": false,
    "clearOnHide": false,
    "refreshOn": "",
    "redrawOn": "",
    "labelPosition": "top",
    "description": "",
    "errorLabel": "",
    "hideLabel": false,
    "autofocus": false,
    "dbIndex": false,
    "customDefaultValue": "",
    "calculateValue": "",
    "calculateServer": false,
    "widget": null,
    "validateOn": "change",
    "validate": {
      "required": false,
      "custom": "",
      "customPrivate": false,
      "strictDateValidation": false,
      "multiple": false,
      "unique": false
    },
    "allowCalculateOverride": false,
    "encrypted": false,
    "showCharCount": false,
    "showWordCount": false,
    "allowMultipleMasks": false,
    "tree": false,
    "components": [{
      "label": "Summeringskonteiner",
      "labelPosition": "top",
      "tooltip": "",
      "customClass": "",
      "hidden": false,
      "hideLabel": true,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "persistent": true,
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "validateOn": "change",
      "errorLabel": "",
      "key": "summeringskonteiner",
      "tags": [],
      "properties": {},
      "conditional": {"show": null, "when": null, "eq": "", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
      "type": "container",
      "input": true,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "refreshOn": "",
      "description": "",
      "tabindex": "",
      "autofocus": false,
      "widget": null,
      "allowCalculateOverride": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "tree": true,
      "components": [{
        "label": "Beløp1",
        "labelPosition": "top",
        "placeholder": "",
        "description": "",
        "tooltip": "",
        "prefix": "",
        "suffix": "",
        "widget": {"type": "input"},
        "customClass": "",
        "tabindex": "",
        "hidden": false,
        "hideLabel": false,
        "mask": false,
        "autofocus": false,
        "spellcheck": true,
        "disabled": false,
        "tableView": false,
        "modalEdit": false,
        "multiple": false,
        "defaultValue": 0,
        "persistent": true,
        "currency": "NOK",
        "inputFormat": "plain",
        "protected": false,
        "dbIndex": false,
        "case": "",
        "encrypted": false,
        "redrawOn": "",
        "clearOnHide": true,
        "customDefaultValue": "",
        "calculateValue": "",
        "calculateServer": false,
        "allowCalculateOverride": false,
        "validateOn": "change",
        "validate": {
          "required": false,
          "customMessage": "",
          "custom": "",
          "customPrivate": false,
          "json": "",
          "strictDateValidation": false,
          "multiple": false,
          "unique": false,
          "min": "",
          "max": "",
          "step": "any",
          "integer": ""
        },
        "unique": false,
        "errorLabel": "",
        "key": "belop1",
        "tags": [],
        "properties": {},
        "conditional": {"show": null, "when": null, "eq": "", "json": ""},
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
        "type": "currency",
        "input": true,
        "delimiter": true,
        "refreshOn": "",
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "id": "en0m32"
      }, {
        "label": "Beløp2",
        "labelPosition": "top",
        "placeholder": "",
        "description": "",
        "tooltip": "",
        "prefix": "",
        "suffix": "",
        "widget": {"type": "input"},
        "customClass": "",
        "tabindex": "",
        "hidden": false,
        "hideLabel": false,
        "mask": false,
        "autofocus": false,
        "spellcheck": true,
        "disabled": false,
        "tableView": false,
        "modalEdit": false,
        "multiple": false,
        "defaultValue": 0,
        "persistent": true,
        "currency": "NOK",
        "inputFormat": "plain",
        "protected": false,
        "dbIndex": false,
        "case": "",
        "encrypted": false,
        "redrawOn": "",
        "clearOnHide": true,
        "customDefaultValue": "",
        "calculateValue": "",
        "calculateServer": false,
        "allowCalculateOverride": false,
        "validateOn": "change",
        "validate": {
          "required": false,
          "customMessage": "",
          "custom": "",
          "customPrivate": false,
          "json": "",
          "strictDateValidation": false,
          "multiple": false,
          "unique": false,
          "min": "",
          "max": "",
          "step": "any",
          "integer": ""
        },
        "unique": false,
        "errorLabel": "",
        "key": "belop2",
        "tags": [],
        "properties": {},
        "conditional": {"show": null, "when": null, "eq": "", "json": ""},
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
        "type": "currency",
        "input": true,
        "delimiter": true,
        "refreshOn": "",
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "id": "emsv0iq"
      }, {
        "label": "Beløp3",
        "labelPosition": "top",
        "placeholder": "",
        "description": "",
        "tooltip": "",
        "prefix": "",
        "suffix": "",
        "widget": {"type": "input"},
        "customClass": "",
        "tabindex": "",
        "hidden": false,
        "hideLabel": false,
        "mask": false,
        "autofocus": false,
        "spellcheck": true,
        "disabled": false,
        "tableView": false,
        "modalEdit": false,
        "multiple": false,
        "defaultValue": 0,
        "persistent": true,
        "currency": "NOK",
        "inputFormat": "plain",
        "protected": false,
        "dbIndex": false,
        "case": "",
        "encrypted": false,
        "redrawOn": "",
        "clearOnHide": true,
        "customDefaultValue": "",
        "calculateValue": "",
        "calculateServer": false,
        "allowCalculateOverride": false,
        "validateOn": "change",
        "validate": {
          "required": false,
          "customMessage": "",
          "custom": "",
          "customPrivate": false,
          "json": "",
          "strictDateValidation": false,
          "multiple": false,
          "unique": false,
          "min": "",
          "max": "",
          "step": "any",
          "integer": ""
        },
        "unique": false,
        "errorLabel": "",
        "key": "belop3",
        "tags": [],
        "properties": {},
        "conditional": {"show": null, "when": null, "eq": "", "json": ""},
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
        "type": "currency",
        "input": true,
        "delimiter": true,
        "refreshOn": "",
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "id": "eqduuye"
      }, {
        "label": "Sum",
        "labelPosition": "top",
        "placeholder": "",
        "description": "",
        "tooltip": "",
        "prefix": "",
        "suffix": "",
        "widget": {"type": "input"},
        "customClass": "",
        "tabindex": "",
        "hidden": false,
        "hideLabel": false,
        "mask": false,
        "autofocus": false,
        "spellcheck": true,
        "disabled": false,
        "tableView": false,
        "modalEdit": false,
        "multiple": false,
        "persistent": true,
        "currency": "nok",
        "inputFormat": "plain",
        "protected": false,
        "dbIndex": false,
        "case": "",
        "encrypted": false,
        "redrawOn": "data",
        "clearOnHide": true,
        "customDefaultValue": "",
        "calculateValue": "value = data.summeringskonteiner.belop1 + data.summeringskonteiner.belop2 + data.summeringskonteiner.belop3;",
        "calculateServer": false,
        "allowCalculateOverride": false,
        "validateOn": "change",
        "validate": {
          "required": false,
          "customMessage": "",
          "custom": "",
          "customPrivate": false,
          "json": "",
          "strictDateValidation": false,
          "multiple": false,
          "unique": false,
          "min": "",
          "max": "",
          "step": "any",
          "integer": ""
        },
        "unique": false,
        "errorLabel": "",
        "key": "sum",
        "tags": [],
        "properties": {},
        "conditional": {"show": null, "when": null, "eq": "", "json": ""},
        "customConditional": "",
        "logic": [],
        "attributes": {},
        "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""},
        "type": "currency",
        "input": true,
        "delimiter": true,
        "refreshOn": "",
        "showCharCount": false,
        "showWordCount": false,
        "allowMultipleMasks": false,
        "id": "e6lbwub",
        "defaultValue": null
      }],
      "id": "eym4bhm"
    }],
    "id": "esu4ts"
  }, {
    "type": "button",
    "label": "Submit",
    "key": "submit",
    "size": "md",
    "block": false,
    "action": "submit",
    "disableOnInvalid": true,
    "theme": "primary",
    "input": true,
    "placeholder": "",
    "prefix": "",
    "customClass": "",
    "suffix": "",
    "multiple": false,
    "defaultValue": null,
    "protected": false,
    "unique": false,
    "persistent": false,
    "hidden": false,
    "clearOnHide": true,
    "refreshOn": "",
    "redrawOn": "",
    "tableView": false,
    "modalEdit": false,
    "labelPosition": "top",
    "description": "",
    "errorLabel": "",
    "tooltip": "",
    "hideLabel": false,
    "tabindex": "",
    "disabled": false,
    "autofocus": false,
    "dbIndex": false,
    "customDefaultValue": "",
    "calculateValue": "",
    "calculateServer": false,
    "widget": {"type": "input"},
    "attributes": {},
    "validateOn": "change",
    "validate": {
      "required": false,
      "custom": "",
      "customPrivate": false,
      "strictDateValidation": false,
      "multiple": false,
      "unique": false
    },
    "conditional": {"show": null, "when": null, "eq": ""},
    "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
    "allowCalculateOverride": false,
    "encrypted": false,
    "showCharCount": false,
    "showWordCount": false,
    "properties": {},
    "allowMultipleMasks": false,
    "leftIcon": "",
    "rightIcon": "",
    "dataGridLabel": true,
    "id": "emp4uih"
  }],
  "display": "wizard",
  "name": "testChristianOgMona",
  "title": "Test Christian og Mona",
  "path": "testchristianogmona",
  "access": [{
    "roles": ["5ee0eaaf7665226ea32fd37b", "5ee0eaaf7665226ea32fd37c", "5ee0eab07665226ea32fd37d"],
    "type": "read_all"
  }],
  "submissionAccess": [],
  "created": "2020-08-03T13:35:34.612Z",
  "modified": "2020-08-13T09:10:39.554Z",
  "machineName": "testChristianOgMona"
}

const createComplexSubmission = () => ({
  "data": {
    "personalia": {
      "fornavn": "Syver",
      "etternavn": "Enstad",
      "fodselsnummerDNummer": "123456 78911"
    },
    "harDuHattAndreInntekter": "nei",
    "inntekt3": 0,
    "sum": 10,
    "tall": 10,
    "summeringskonteiner": {"sum": 3702},
  },
  "metadata": {
    "timezone": "Europe/Oslo",
    "offset": 120,
    "origin": "http://localhost:3000",
    "referrer": "http://localhost:3000/skjema/nynav760710registreringsskjemafortilskuddtilutdanning",
    "browserName": "Netscape",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
    "pathName": "/skjema/testchristianogmona",
    "onLine": true
  },
  "state": "submitted"
});

const createComplexFormDefinition = () => ({
  "_id": "5f2812a61cd355000301f0d0",
  "type": "form",
  "tags": ["nav-skjema"],
  "owner": "5ee0eacc7665226ea32fd389",
  "display": "wizard",
  "name": "testChristianOgMona",
  "title": "Test Christian og Mona",
  "path": "testchristianogmona",
  "access": [{
    "roles": ["5ee0eaaf7665226ea32fd37b", "5ee0eaaf7665226ea32fd37c", "5ee0eab07665226ea32fd37d"],
    "type": "read_all"
  }],
  "created": "2020-08-03T13:35:34.612Z",
  "modified": "2020-08-13T09:10:39.554Z",
  "machineName": "testChristianOgMona",
  "components": [
    {
      "label": "HTML",
      "key": "html",
      "type": "htmlelement",
      "input": false,
      "id": "e5lcez"
    },
    {
      "title": "Personalia",
      "key": "personalia1",
      "type": "panel",
      "label": "Panel",
      "input": false,
      "id": "edfcko9",
      "components": [
        {
          "label": "Personalia",
          "key": "personalia",
          "type": "container",
          "input": true,
          "id": "ehnaj4mb",
          "components": [
            {
              "label": "Fornavn",
              "type": "textfield",
              "key": "fornavn",
              "input": true,
              "placeholder": "Fornavn",
              "id": "e2i3kg5"
            },
            {
              "label": "Etternavn",
              "type": "textfield",
              "key": "etternavn",
              "input": true,
              "placeholder": "Etternavn",
              "id": "eu4ap99"
            },
            {
              "key": "fodselsnummerDNummer",
              "type": "fnrfield",
              "input": true,
              "label": "Fødselsnummer / D-nummer",
              "id": "ecrz8yq"
            }
          ],
        },
        {
          "label": "Har du hatt andre inntekter?",
          "values": [{"label": "Ja", "value": "ja", "shortcut": ""}, {"label": "Nei", "value": "nei", "shortcut": ""}],
          "key": "harDuHattAndreInntekter",
          "type": "radio",
          "input": true,
          "id": "ekmagkp",
        },
        {
          "label": "Inntekt",
          "key": "inntekt3",
          "type": "currency",
          "input": true,
          "id": "ei5wbp"
        },
        {
          "label": "Sum",
          "key": "sum",
          "type": "currency",
          "input": true,
          "id": "e5cym5",
        },
        {
          "label": "Tall",
          "key": "tall",
          "type": "number",
          "input": true,
          "id": "exkmmf8",
        }],
    },
    {
      "title": "Summeringstest",
      "key": "summeringstest",
      "type": "panel",
      "label": "Panel",
      "input": false,
      "id": "esu4ts",
      "components": [{
        "label": "Summeringskonteiner",
        "key": "summeringskonteiner",
        "type": "container",
        "input": true,
        "id": "eym4bhm",
        "components": [
          {
          "label": "Sum",
          "key": "sum",
          "type": "currency",
          "input": true,
          "id": "e6lbwub",
        }]
      }],
    },
    ],
});

const createSubmission = () => ({
  "state": "submitted",
  "data": {
    "tekstfelt": "dfghjk",
    "T": "tcfghj",
    "submit": true,
    "sum": 3957,
    "belop": 3456,
    "belop1": 456,
    "belop2": 45
  },
  "metadata": {
    "timezone": "Europe/Oslo",
    "offset": 120,
    "origin": "https://skjema.dev.nav.no",
    "referrer": "",
    "browserName": "Netscape",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36",
    "pathName": "/skjema/test56789",
    "onLine": true
  }
});

const createForm = () => ({
  "_id": "5f20154e0018c900032fa00f",
  "type": "form",
  "tags": ["nav-skjema"],
  "owner": "5ee0eacc7665226ea32fd389",
  "display": "form",
  "name": "test56789",
  "title": "test56789",
  "path": "test56789",
  "machineName": "test56789",
  "components": [
    {
      "label": "Tekstfelt",
      "key": "tekstfelt",
      "type": "textfield",
      "input": true,
      "id": "e3nxyxr",
    },
    {
      "label": "2345t",
      "key": "T",
      "type": "textfield",
      "input": true,
      "id": "edawfax"
    },
    {
      "label": "Beløp",
      "key": "belop",
      "type": "currency",
      "input": true,
      "id": "edo3ppo",
    },
    {
      "label": "Beløp",
      "key": "belop1",
      "type": "currency",
      "input": true,
      "id": "edsy44",
    },
    {
      "label": "Beløp",
      "key": "belop2",
      "type": "currency",
      "input": true,
      "id": "eg92i4j",
    },
    {
      "label": "Sum",
      "key": "sum",
      "type": "currency",
      "input": true,
      "id": "e5guh0h",
    },
    {
      "type": "button",
      "label": "Send inn",
      "key": "submit",
      "action": "submit",
      "input": true,
      "id": "ekuuti"
    }]
});

describe('generating doc definition', () => {
  it('generates the docDef for an empty submission', () => {
    const submission = {data: {}, metadata: {}};
    const form = {components: []};
    const generator = new Pdfgen(submission, form);
    const doc_definition = generator.generateDocDefinition();
    expect(doc_definition).toEqual({
      styles: {
        "anotherStyle": {
          "alignment": "right",
          "italics": true
        },
        "header": {
          "bold": true,
          "fontSize": 22
        }
      },
      content: [
        {
          "style": "header",
          "text": "Skjemainnsendingskvittering"
        },
        "Her står det så mye tekst at den bryter over mer enn en linje, bare for å at vi " +
        "skal se hvordan overskrift og brødtekst ser ut",
        {
          "layout": "lightHorizontalLines",
          "table": {
            "body": [
              [
                "Label",
                "Value"
              ]
            ],
            "headerRows": 1,
            "widths": [
              "*",
              "*"
            ]
          }
        }
      ]
    });
  });

  it('generates table from form and submission', () => {
    const submission = createSubmission();
    const form = createForm();
    const generator = new Pdfgen(submission, form);
    const doc_definition = generator.generateDocDefinition();
    const tableDef = doc_definition.content[2]
    expect(tableDef.table).toBeDefined();
    const tableData = tableDef.table.body.slice(1);
    expect(tableData).toHaveLength(Object.keys(submission.data).length); // header row
    expect(tableData).toEqual([
      ['Tekstfelt', "dfghjk"],
      ['2345t', 'tcfghj'],
      ['Beløp', 3456],
      ['Beløp', 456],
      ['Beløp', 45],
      ['Sum', 3957],
      ['Send inn', true],
    ])
  });

  it('generates table for a complex form', () => {
    const submission = createComplexSubmission();
    const form = createComplexFormDefinition();
    const generator = new Pdfgen(submission, form);
    const doc_definition = generator.generateDocDefinition();
    const tableDef = doc_definition.content[2]
    expect(tableDef.table).toBeDefined();
    const tableData = tableDef.table.body.slice(1);
    expect(tableData).toEqual([
      ['Personalia: Fornavn', "Syver"],
      ['Personalia: Etternavn', 'Enstad'],
      ['Personalia: Fødselsnummer / D-nummer', "123456 78911"],
      ['Har du hatt andre inntekter?', 'Nei'],
      ['Inntekt', 0],
      ['Sum', 10],
      ['Tall', 10],
      ['Summeringskonteiner: Sum', 3702]
    ])
  });

});