export default {
  "html": "<h2>&lt;Skriv tittel på søknad her&gt;</h2>",
  "label": "Content",
  "customClass": "",
  "refreshOnChange": false,
  "hidden": false,
  "tableView": false,
  "modalEdit": false,
  "key": "content",
  "tags": [],
  "properties": {},
  "conditional": { "show": null, "when": null, "eq": "", "json": "" },
  "customConditional": "",
  "logic": [],
  "attributes": {},
  "overlay": { "style": "", "page": "", "left": "", "top": "", "width": "", "height": "" },
  "type": "content",
  "input": false,
  "placeholder": "",
  "prefix": "",
  "suffix": "",
  "multiple": false,
  "defaultValue": null,
  "protected": false,
  "unique": false,
  "persistent": true,
  "clearOnHide": true,
  "refreshOn": "",
  "redrawOn": "",
  "labelPosition": "top",
  "description": "",
  "errorLabel": "",
  "tooltip": "",
  "hideLabel": false,
  "tabindex": "",
  "disabled": false,
  "autofocus": false,
  "dbIndex": false,
  "customDefaultValue": "",
  "calculateValue": "",
  "calculateServer": false,
  "widget": null,
  "validateOn": "change",
  "validate": {
    "required": false,
    "custom": "",
    "customPrivate": false,
    "strictDateValidation": false,
    "multiple": false,
    "unique": false,
  },
  "allowCalculateOverride": false,
  "encrypted": false,
  "showCharCount": false,
  "showWordCount": false,
  "allowMultipleMasks": false,
  "id": "title",
}
