ingresses:
- "https://skjemabygging-formio.dev.intern.nav.no"
image: {{image}}
publiseringWorkflowDispatchRef: "dev-publisering"
skjemabygging-proxy-host: skjemabygging-proxy.dev-fss-pub.nais.io
skjemabygging-proxy-client-id: 95170319-b4d7-4190-8271-118ed19bafbf
skjemabygging-proxy-url: https://skjemabygging-proxy.dev-fss-pub.nais.io
accessPolicy:
  outbound:
    rules:
      - application: skjemabygging-proxy
        namespace: skjemadigitalisering
        cluster: dev-fss
