apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "skjemabygging-formio"
  namespace: "skjemadigitalisering"
  labels:
    "team": "skjemadigitalisering"
spec:
  image: {{image}}
  liveness:
    path: "/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  ingresses:
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
  env:
    - name: PUBLISH_REPO
      value: {{publish-repo}}
    - name: PUBLISH_REPO_OWNER
      value: {{publish-repo-owner}}
    - name: PUBLISH_REPO_BASE
      value: {{publish-repo-base}}
    - name: SKJEMABYGGING_PROXY_URL
      value: {{skjemabygging-proxy-url}}
    - name: SKJEMABYGGING_PROXY_CLIENT_ID
      value: {{skjemabygging-proxy-client-id}}
  envFrom:
    - secret: monorepo-poc-akg
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
      {{#each accessPolicy.outbound.rules}}
        - application: {{this.application}}
          namespace: {{this.namespace}}
          cluster: {{this.cluster}}
      {{/each}}
      external:
        - host: formio-api-server.ekstern.dev.nav.no
        - host: api.github.com
        - host: {{skjemabygging-proxy-host}}
