apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app-name}}
  namespace: "skjemadigitalisering"
  labels:
    "team": "skjemadigitalisering"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  ingresses:
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
  env:
    - name: FYLLUT_BASE_URL
      value: {{fyllut-base-url}}
    - name: ENABLED_FEATURES
      value: {{enabled-features}}
    - name: PUBLISH_REPO
      value: {{publish-repo}}
    - name: PUBLISH_REPO_OWNER
      value: {{publish-repo-owner}}
    - name: PUBLISH_REPO_BASE
      value: {{publish-repo-base}}
    - name: SKJEMABYGGING_PROXY_URL
      value: {{skjemabygging-proxy-url}}
    - name: SKJEMABYGGING_PROXY_CLIENT_ID
      value: {{skjemabygging-proxy-client-id}}
  envFrom:
  {{#each secrets as |secret|}}
    - secret: {{secret}}
  {{/each}}
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: false
      claims:
        groups:
          - id: 1d12af59-d953-4f85-9f65-d8cbf6672deb
          - id: 0c0e4023-5fd3-4cfe-8b40-3b98645bb08f
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /notifications
  accessPolicy:
    outbound:
      rules:
      {{#each accessPolicy.outbound.rules}}
        - application: {{this.application}}
          namespace: {{this.namespace}}
          cluster: {{this.cluster}}
      {{/each}}
      external:
        - host: formio-api-server.ekstern.dev.nav.no
        - host: api.github.com
        - host: formio-api.nav.no
        - host: api-eu.pusher.com
      {{#each accessPolicy.outbound.external}}
        - host: {{this.host}}
      {{/each}}
