app-name: skjemabygging
env-name: prod-gcp
logs-url: https://logs.adeo.no/app/r/s/aRKKp
special-type-to-use-in-alertmanager-config: "fyllut-sendinn-alerts"
ingresses:
- "https://skjemabygging.nav.no"
publish-repo: skjemautfylling-formio
publish-repo-owner: navikt
publish-repo-base: master
skjemabygging-proxy-client-id: 031863f2-9881-44af-ace5-6b5ab52afeb1
skjemabygging-proxy-url: https://skjemabygging-proxy.prod-fss-pub.nais.io
accessPolicy:
  outbound:
    rules:
      - application: skjemabygging-proxy
        namespace: skjemadigitalisering
        cluster: prod-fss
    external:
      - host: skjemabygging-proxy.prod-fss-pub.nais.io
secrets:
  - bygger
  - bygger-pusher
  - github-app-installation
