export default [
  {
    label: "HTML",
    tag: "h2",
    className: "",
    attrs: [{ attr: "", value: "" }],
    content: "--Sett inn tittel her--",
    refreshOnChange: false,
    customClass: "",
    hidden: false,
    tableView: false,
    modalEdit: false,
    key: "html",
    tags: [],
    properties: {},
    conditional: { show: null, when: null, eq: "", json: "" },
    customConditional: "",
    logic: [],
    attributes: {},
    overlay: { style: "", page: "", left: "", top: "", width: "", height: "" },
    type: "htmlelement",
    input: false,
    placeholder: "",
    prefix: "",
    suffix: "",
    multiple: false,
    defaultValue: null,
    protected: false,
    unique: false,
    persistent: false,
    clearOnHide: true,
    refreshOn: "",
    redrawOn: "",
    labelPosition: "top",
    description: "",
    errorLabel: "",
    tooltip: "",
    hideLabel: false,
    tabindex: "",
    disabled: false,
    autofocus: false,
    dbIndex: false,
    customDefaultValue: "",
    calculateValue: "",
    calculateServer: false,
    widget: null,
    validateOn: "change",
    validate: {
      required: false,
      custom: "",
      customPrivate: false,
      strictDateValidation: false,
      multiple: false,
      unique: false,
    },
    allowCalculateOverride: false,
    encrypted: false,
    showCharCount: false,
    showWordCount: false,
    allowMultipleMasks: false,
    id: "eiqwd8",
  },
];
