import { FormBuilderSchemas } from "@navikt/skjemadigitalisering-shared-components";

const { firstNameSchema, surnameSchema } = FormBuilderSchemas;

const sokerPostfix = "Soker";

export const defaultFormFields = () => [
  {
    type: "panel",
    input: false,
    title: "Veiledning",
    key: "veiledning",
    theme: "default",
    components: [
      {
        label: "Veiledningstekst",
        type: "htmlelement",
        key: "veiledningstekst",
        input: false,
        content: "Her skal det stå litt informasjon om søknaden",
      },
    ],
  },
  {
    type: "panel",
    input: false,
    title: "Dine opplysninger",
    key: "personopplysninger",
    theme: "default",
    components: [
      firstNameSchema(sokerPostfix),
      surnameSchema(sokerPostfix),
      {
        key: "harDuNorskFodselsnummerEllerDNummer",
        type: "radiopanel",
        input: true,
        validateOn: "blur",
        tableView: false,
        label: "Har du norsk fødselsnummer eller D-nummer?",
        values: [
          {
            value: "ja",
            label: "Ja",
          },
          {
            value: "nei",
            label: "Nei",
          },
        ],
        validate: {
          required: true,
        },
      },
      {
        label: "Fødselsnummer / D-nummer",
        key: "fodselsnummerDNummer",
        type: "fnrfield",
        input: true,
        tableView: true,
        conditional: {
          show: true,
          when: "harDuNorskFodselsnummerEllerDNummer",
          eq: "ja",
        },
      },
      {
        visArvelger: true,
        label: "Fødselsdato (dd.mm.åååå)",
        mayBeEqual: false,
        key: "fodselsdatoDdMmAaaa",
        type: "navDatepicker",
        dataGridLabel: true,
        input: true,
        tableView: false,
        validate: {
          required: true,
          custom:
            "valid = instance.validateDatePicker(input, data,component.beforeDateInputKey, component.mayBeEqual, component.earliestAllowedDate, component.latestAllowedDate);",
        },
        validateOn: "blur",
        conditional: {
          show: true,
          when: "harDuNorskFodselsnummerEllerDNummer",
          eq: "nei",
        },
      },
      {
        content:
          'NAV sender svar på søknad og annen kommunikasjon til din folkeregistrerte adresse. \n<br>\nDu kan <a href="https://www.skatteetaten.no/person/folkeregister/flytte/endre-postadresse/" target="_blank">sjekke og endre din folkeregistrerte adresse på skatteetatens nettsider (åpnes i et nytt vindu).</a>\nHvis du ønsker å motta kommunikasjon fra NAV på en annen adresse enn din folkeregistrerte adresse, kan du bruke lenken ovenfor til å oppgi en postadresse i Folkeregisteret.\nDu finner også papirskjema for å endre postadresse på samme siden hos Skatteetaten.',
        key: "alertstripe",
        type: "alertstripe",
        label: "Alertstripe",
        alerttype: "info",
        input: true,
        tableView: false,
        conditional: {
          show: true,
          when: "harDuNorskFodselsnummerEllerDNummer",
          eq: "ja",
        },
      },
      {
        label: "Bor du i Norge?",
        key: "borDuINorge",
        type: "radiopanel",
        input: true,
        validateOn: "blur",
        tableView: false,
        values: [
          {
            value: "ja",
            label: "Ja",
          },
          {
            value: "nei",
            label: "Nei",
          },
        ],
        validate: {
          required: true,
        },
        conditional: {
          show: true,
          when: "harDuNorskFodselsnummerEllerDNummer",
          eq: "nei",
        },
      },
      {
        label: "Er kontaktadressen din en vegadresse eller postboksadresse",
        key: "gateadresseEllerPostboksadresse",
        type: "radiopanel",
        input: true,
        validateOn: "blur",
        tableView: false,
        values: [
          {
            value: "vegadresse",
            label: "Vegadresse",
          },
          {
            value: "postboksadresse",
            label: "Postboksadresse",
          },
        ],
        validate: {
          required: true,
        },
        conditional: {
          show: true,
          when: "borDuINorge",
          eq: "ja",
        },
      },
      {
        legend: "Kontaktadresse",
        key: "navSkjemagruppe",
        type: "navSkjemagruppe",
        label: "Kontaktadresse",
        conditional: {
          show: true,
          when: "gateadresseEllerPostboksadresse",
          eq: "vegadresse",
        },
        components: [
          {
            label: "C/O",
            fieldSize: "input--xxl",
            validateOn: "blur",
            key: "cO",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            label: "Gatenavn",
            fieldSize: "input--xxl",
            autocomplete: "street-address",
            validateOn: "blur",
            key: "gatenavn",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
            validate: {
              required: true,
            },
          },
          {
            label: "Husnummer (og evt. bokstav)",
            fieldSize: "input--xs",
            validateOn: "blur",
            key: "husnummer",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            label: "Bolignummer",
            fieldSize: "input--xxl",
            validateOn: "blur",
            key: "leilighetsnummer",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            label: "Postnummer",
            fieldSize: "input--xs",
            autocomplete: "postal-code",
            spellcheck: false,
            validateOn: "blur",
            validate: {
              required: true,
              minLength: 4,
              maxLength: 4,
            },
            key: "postnr1",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            label: "Poststed",
            fieldSize: "input--xxl",
            autocomplete: "address-level2",
            validateOn: "blur",
            validate: {
              required: true,
            },
            key: "poststed",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            visArvelger: true,
            label: "Gyldig fra og med dato (dd.mm.åååå)",
            mayBeEqual: false,
            validate: {
              required: true,
              custom:
                "valid = instance.validateDatePicker(input, data,component.beforeDateInputKey, component.mayBeEqual, component.earliestAllowedDate, component.latestAllowedDate);",
            },
            validateOn: "blur",
            key: "gyldigFraDatoDdMmAaaa1",
            type: "navDatepicker",
            dataGridLabel: true,
            input: true,
            tableView: false,
          },
          {
            visArvelger: true,
            label: "Gyldig til og med dato (dd.mm.åååå)",
            description:
              "Du velger selv hvor lenge adressen skal være gyldig, maksimalt 1 år. Etter 1 år må du endre eller forlenge adressen.",
            beforeDateInputKey: "gyldigFraDatoDdMmAaaa1",
            mayBeEqual: false,
            validate: {
              custom:
                "valid = instance.validateDatePicker(input, data,component.beforeDateInputKey, component.mayBeEqual, component.earliestAllowedDate, component.latestAllowedDate);",
            },
            validateOn: "blur",
            key: "gyldigTilDatoDdMmAaaa1",
            type: "navDatepicker",
            dataGridLabel: true,
            input: true,
            tableView: false,
            latestAllowedDate: 365,
          },
        ],
        input: false,
        tableView: false,
      },
      {
        legend: "Kontaktadresse",
        key: "navSkjemagruppe1",
        type: "navSkjemagruppe",
        label: "Kontaktadresse",
        conditional: {
          show: true,
          when: "gateadresseEllerPostboksadresse",
          eq: "postboksadresse",
        },
        components: [
          {
            label: "Navn på eier av postboksen",
            fieldSize: "input--xxl",
            validateOn: "blur",
            key: "navnPaEierAvPostboksen",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            label: "Postboks",
            fieldSize: "input--s",
            validateOn: "blur",
            validate: {
              required: true,
            },
            key: "postboks",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            label: "Postnummer",
            fieldSize: "input--xs",
            autocomplete: "postal-code",
            spellcheck: false,
            validateOn: "blur",
            validate: {
              required: true,
              minLength: 4,
              maxLength: 4,
            },
            key: "postnr",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            label: "Poststed",
            fieldSize: "input--xxl",
            autocomplete: "address-level2",
            validateOn: "blur",
            validate: {
              required: true,
            },
            key: "poststed1",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            visArvelger: true,
            label: "Gyldig fra og med dato (dd.mm.åååå)",
            mayBeEqual: false,
            validate: {
              required: true,
              custom:
                "valid = instance.validateDatePicker(input, data,component.beforeDateInputKey, component.mayBeEqual, component.earliestAllowedDate, component.latestAllowedDate);",
            },
            validateOn: "blur",
            key: "gyldigFraDatoDdMmAaaa2",
            type: "navDatepicker",
            dataGridLabel: true,
            input: true,
            tableView: false,
          },
          {
            visArvelger: true,
            label: "Gyldig til og med dato (dd.mm.åååå)",
            description:
              "Du velger selv hvor lenge adressen skal være gyldig, maksimalt 1 år. Etter 1 år må du endre eller forlenge adressen.",
            beforeDateInputKey: "gyldigFraDatoDdMmAaaa2",
            mayBeEqual: false,
            validate: {
              custom:
                "valid = instance.validateDatePicker(input, data,component.beforeDateInputKey, component.mayBeEqual, component.earliestAllowedDate, component.latestAllowedDate);",
            },
            validateOn: "blur",
            key: "gyldigTilDatoDdMmAaaa2",
            type: "navDatepicker",
            dataGridLabel: true,
            input: true,
            tableView: false,
            latestAllowedDate: 365,
          },
        ],
        input: false,
        tableView: false,
      },
      {
        legend: "Utenlandsk kontaktadresse",
        key: "navSkjemagruppe2",
        conditional: {
          show: true,
          when: "borDuINorge",
          eq: "nei",
        },
        type: "navSkjemagruppe",
        label: "Utenlandsk kontaktadresse",
        components: [
          {
            label: "C/O",
            fieldSize: "input--xxl",
            validateOn: "blur",
            key: "cO1",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            label: "Gatenavn og husnummer, evt. postboks",
            fieldSize: "input--xxl",
            autocomplete: "street-address",
            validateOn: "blur",
            validate: {
              required: true,
            },
            key: "gatenavnOgHusnummer",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            label: "Bygning",
            fieldSize: "input--xxl",
            validateOn: "blur",
            key: "bygningEtasjeLeilighet",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            label: "Postkode",
            fieldSize: "input--s",
            validateOn: "blur",
            key: "postkode",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            label: "By / stedsnavn",
            fieldSize: "input--xxl",
            validateOn: "blur",
            key: "bySted",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            label: "Region",
            fieldSize: "input--xxl",
            validateOn: "blur",
            key: "regionDistriktOmrade",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            label: "Land",
            fieldSize: "input--xxl",
            autocomplete: "country-name",
            validateOn: "blur",
            validate: {
              required: true,
            },
            key: "land",
            type: "textfield",
            input: true,
            dataGridLabel: true,
            tableView: true,
          },
          {
            visArvelger: true,
            label: "Gyldig fra og med dato (dd.mm.åååå)",
            mayBeEqual: false,
            validate: {
              required: true,
              custom:
                "valid = instance.validateDatePicker(input, data,component.beforeDateInputKey, component.mayBeEqual, component.earliestAllowedDate, component.latestAllowedDate);",
            },
            validateOn: "blur",
            key: "gyldigFraDatoDdMmAaaa",
            type: "navDatepicker",
            dataGridLabel: true,
            input: true,
            tableView: false,
          },
          {
            visArvelger: true,
            label: "Gyldig til og med dato (dd.mm.åååå)",
            description:
              "Du velger selv hvor lenge adressen skal være gyldig, maksimalt 1 år. Etter 1 år må du endre eller forlenge adressen.",
            beforeDateInputKey: "gyldigFraDatoDdMmAaaa",
            mayBeEqual: false,
            validate: {
              required: true,
              custom:
                "valid = instance.validateDatePicker(input, data,component.beforeDateInputKey, component.mayBeEqual, component.earliestAllowedDate, component.latestAllowedDate);",
            },
            validateOn: "blur",
            key: "gyldigTilDatoDdMmAaaa",
            type: "navDatepicker",
            dataGridLabel: true,
            input: true,
            tableView: false,
          },
        ],
        input: false,
        tableView: false,
      },
    ],
  },
  {
    type: "panel",
    input: false,
    title: "Vedlegg",
    key: "vedlegg",
    theme: "default",
    components: [
      {
        label: "Annen dokumentasjon",
        description: "Har du noen annen dokumentasjon du ønsker å legge ved?",
        type: "radiopanel",
        key: "vedlegg",
        input: true,
        clearOnHide: true,
        validate: {
          required: true,
        },
        properties: {
          vedleggstittel: "Annet",
          vedleggskode: "N6",
        },
        values: [
          {
            value: "leggerVedNaa",
            label: "Ja, jeg legger det ved denne søknaden.",
          },
          {
            value: "ettersender",
            label: "Jeg ettersender dokumentasjonen senere.",
          },
          {
            value: "nei",
            label: "Nei, jeg har ingen ekstra dokumentasjon jeg vil legge ved.",
          },
        ],
      },
    ],
  },
];
