apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app-name}}
  namespace: "skjemadigitalisering"
  labels:
    "team": "skjemadigitalisering"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  image: {{image}}
  port: 8080
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  liveness:
    path: "/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  ingresses:
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
  env:
    - name: FYLLUT_BASE_URL
      value: {{fyllut-base-url}}
    - name: ENABLED_FEATURES
      value: {{enabled-features}}
    - name: PUBLISH_REPO
      value: {{publish-repo}}
    - name: PUBLISH_REPO_OWNER
      value: {{publish-repo-owner}}
    - name: PUBLISH_REPO_BASE
      value: {{publish-repo-base}}
    - name: SKJEMABYGGING_PROXY_URL
      value: {{skjemabygging-proxy-url}}
    - name: SKJEMABYGGING_PROXY_CLIENT_ID
      value: {{skjemabygging-proxy-client-id}}
    - name: FORMS_API_URL
      value: http://forms-api.fyllut-sendinn
    {{#each environmentVars}}
    - name: {{this.name}}
      value: {{this.value}}
    {{/each}}
    {{#each azure.ad_groups}}
    - name: "FORMS_API_AD_GROUP_{{this.type}}"
      value: "{{this.id}}"
    {{/each }}
  envFrom:
  {{#each secrets as |secret|}}
    - secret: {{secret}}
  {{/each}}
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
        {{#each azure.ad_groups}}
          - id: "{{this.id}}"
        {{/each}}
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /notifications
  accessPolicy:
    outbound:
      rules:
        - application: forms-api
          namespace: fyllut-sendinn
      {{#each accessPolicy.outbound.rules}}
        - application: {{this.application}}
          namespace: {{this.namespace}}
          cluster: {{this.cluster}}
      {{/each}}
      external:
        - host: api.github.com
        - host: api-eu.pusher.com
      {{#each accessPolicy.outbound.external}}
        - host: {{this.host}}
      {{/each}}
