---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app-name}}
  namespace: skjemadigitalisering
  labels:
    team: skjemadigitalisering
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  team: skjemadigitalisering
  port: 8080
  azure:
    application:
      enabled: true
      tenant: {{azure.application.tenant}}
  idporten:
    enabled: true
    accessTokenLifetime: 3600
    sessionLifetime: 7200
    sidecar:
      enabled: true
      locale: nb
      autoLogin: false
  tokenx:
    enabled: true
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /fyllut/internal/isAlive
    initialDelay: 10
  readiness:
    path: /fyllut/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true  # default: false. Pod will now be scraped for metrics by Prometheus.
    path: /fyllut/internal/metrics # Path where prometheus metrics are served.
  accessPolicy:
    inbound:
      rules:
        - application: fyllut-ettersending
    outbound:
      rules:
      {{#each accessPolicy.outbound.rules}}
        - application: {{this.application}}
          namespace: {{this.namespace}}
          cluster: {{this.cluster}}
      {{/each}}
      external:
        - host: {{dekorator-host}}
        - host: {{foersteside-host}}
        - host: {{skjemabygging-proxy-host}}
  env:
    - name: DECORATOR_URL
      value: {{dekorator-url}}
    - name: FOERSTESIDE_URL
      value: {{foersteside-url}}
    - name: FORMS_SOURCE
      value: {{forms-source}}
    - name: SKJEMABYGGING_PROXY_URL
      value: {{skjemabygging-proxy-url}}
    - name: SKJEMABYGGING_PROXY_CLIENT_ID
      value: {{skjemabygging-proxy-client-id}}
    - name: PDL_TOKEN_SCOPE_CLUSTER
      value: {{pdl-token-scope-cluster}}
  envFrom:
  {{#each secrets as |secret|}}
    - secret: {{secret}}
  {{/each}}
