app-name: skjemautfylling
ingresses:
  - "https://skjemautfylling-formio.dev.nav.no/fyllut"
image: {{image}}
foersteside-host: www.nav.no
foersteside-url: https://www.nav.no/soknader/api/forsteside
dekorator-host: www.nav.no
dekorator-url: https://www.nav.no/dekoratoren?simple=true
skjemabygging-proxy-host: skjemabygging-proxy.dev-fss-pub.nais.io
skjemabygging-proxy-client-id: 95170319-b4d7-4190-8271-118ed19bafbf
skjemabygging-proxy-url: https://skjemabygging-proxy.dev-fss-pub.nais.io
forms-source: "static"
secrets:
  - sentry-dsn
azure:
  application:
    tenant: trygdeetaten.no
accessPolicy:
  outbound:
    rules:
      - application: skjemabygging-proxy
        namespace: skjemadigitalisering
        cluster: dev-fss