app-name: skjemautfylling
ingresses:
  - "https://skjemautfylling-formio.intern.dev.nav.no/fyllut"
enabled-features: translations,sendInnIntegration
foersteside-url: https://www.nav.no/soknader/api/forsteside
dekorator-url: https://www.nav.no/dekoratoren?simple=true
skjemabygging-proxy-client-id: 95170319-b4d7-4190-8271-118ed19bafbf
skjemabygging-proxy-url: https://skjemabygging-proxy.dev-fss-pub.nais.io
send-inn-token-x-client-id: dev-gcp:team-soknad:innsending-api
send-inn-host: http://innsending-api.team-soknad
forms-source: "static"
pdl-token-scope-cluster: "dev-fss"
secrets:
  - sentry-dsn
azure:
  application:
    tenant: trygdeetaten.no
accessPolicy:
  outbound:
    rules:
      - application: skjemabygging-proxy
        namespace: skjemadigitalisering
        cluster: dev-fss
      - application: innsending-api
        namespace: team-soknad
        cluster: dev-gcp
      - application: pdl-api
        namespace: pdl
        cluster: dev-fss
      - application: nav-dekoratoren
        namespace: personbruker
        cluster: dev-gcp
    external:
      - host: skjemabygging-proxy.dev-fss-pub.nais.io
      - host: formio-api.intern.dev.nav.no
