app-name: skjemautfylling
ingresses:
  - "https://www.nav.no/fyllut"
image: {{image}}
foersteside-url: https://www.nav.no/soknader/api/forsteside
dekorator-url: https://www.nav.no/dekoratoren?simple=true
skjemabygging-proxy-client-id: 031863f2-9881-44af-ace5-6b5ab52afeb1
skjemabygging-proxy-url: https://skjemabygging-proxy.prod-fss-pub.nais.io
forms-source: "static"
pdl-token-scope-cluster: "prod-fss"
secrets:
  - sentry-dsn
  - fyllut-features
  - digital-innsending
azure:
  application:
    tenant: nav.no
accessPolicy:
  outbound:
    rules:
      - application: skjemabygging-proxy
        namespace: skjemadigitalisering
        cluster: prod-fss
      - application: innsending-api
        namespace: team-soknad
        cluster: prod-gcp
      - application: pdl-api
        namespace: pdl
        cluster: prod-fss
    external:
      - host: www.nav.no
      - host: skjemabygging-proxy.prod-fss-pub.nais.io
      - host: tokendings.prod-gcp.nais.io
      - host: formio-api.intern.nav.no