app-name: skjemautfylling
ingresses:
  - "https://www.nav.no/fyllut"
image: {{image}}
foersteside-host: www.nav.no
foersteside-url: https://www.nav.no/soknader/api/forsteside
dekorator-host: www.nav.no
dekorator-url: https://www.nav.no/dekoratoren?simple=true
skjemabygging-proxy-host: skjemabygging-proxy.prod-fss-pub.nais.io
skjemabygging-proxy-client-id: 031863f2-9881-44af-ace5-6b5ab52afeb1
skjemabygging-proxy-url: https://skjemabygging-proxy.prod-fss-pub.nais.io
forms-source: "static"
enabled-features: "translations"
secrets:
  - sentry-dsn
  - digital-innsending
azure:
  application:
    tenant: nav.no
accessPolicy:
  outbound:
    rules:
      - application: skjemabygging-proxy
        namespace: skjemadigitalisering
        cluster: prod-fss
      - application: innsending-api
        namespace: team-soknad
        cluster: prod-gcp
