app-name: skjemautfylling
ingresses:
  - "https://www.nav.no/fyllut"
replicas-min: 3
replicas-max: 6
enabled-features: ""
foersteside-url: https://www.nav.no/soknader/api/forsteside
dekorator-url: https://www.nav.no/dekoratoren?simple=true
skjemabygging-proxy-client-id: 031863f2-9881-44af-ace5-6b5ab52afeb1
skjemabygging-proxy-url: https://skjemabygging-proxy.prod-fss-pub.nais.io
gotenberg-url: http://upload-convert-to-pdf.fyllut-sendinn
gotenberg-url-en: http://upload-convert-to-pdf-en.fyllut-sendinn
send-inn-token-x-client-id: prod-gcp:team-soknad:innsending-api
send-inn-host: http://innsending-api.team-soknad
tilleggsstonader-token-x-client-id: dev-gcp:tilleggsstonader:tilleggsstonader-integrasjoner
tilleggsstonader-integrasjoner-host: http://tilleggsstonader-integrasjoner.tilleggsstonader
kodeverk:
  url: http://kodeverk-api.team-rocket
  scope: prod-gcp.team-rocket.kodeverk-api
forms-source: "static"
pdl-token-scope-cluster: "prod-fss"
environmentVars: []
azure:
  application:
    tenant: nav.no
accessPolicy:
  inbound:
    rules:
      - application: fyllut-ettersending
      - application: send-inn-frontend
        namespace: team-soknad
  outbound:
    rules:
      - application: skjemabygging-proxy
        namespace: skjemadigitalisering
        cluster: prod-fss
      - application: innsending-api
        namespace: team-soknad
        cluster: prod-gcp
      - application: upload-convert-to-pdf
        namespace: fyllut-sendinn
        cluster: prod-gcp
      - application: upload-convert-to-pdf-en
        namespace: fyllut-sendinn
      - application: tilleggsstonader-integrasjoner
        namespace: tilleggsstonader
        cluster: prod-gcp
      - application: pdl-api
        namespace: pdl
        cluster: prod-fss
      - application: nav-dekoratoren
        namespace: personbruker
        cluster: prod-gcp
      - application: kodeverk-api
        namespace: team-rocket
        cluster: prod-gcp
      - application: forms-api
        namespace: fyllut-sendinn
        cluster: prod-gcp
    external:
      - host: skjemabygging-proxy.prod-fss-pub.nais.io
      - host: formio-api.intern.nav.no
