name: Continous integration | deployment
on: push

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/skjemautfylling:${{ github.sha }}
  PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
  PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
  PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
  PUSHER_APP_CLUSTER: ${{ secrets.PUSHER_APP_CLUSTER }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: 'true'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Npm Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Cache server node modules
        id: cache-server-node-modules
        uses: actions/cache@v2
        with:
          path: server/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('server/package-lock.json') }}
      - name: Install frontend deps
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test frontend
        run: npm test
      - run: npm run build
      - name: Install server deps
        if: steps.cache-server-node-modules.outputs.cache-hit != 'true'
        run: cd server && npm ci
      - name: Test server
        run: cd server && npm test
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_output
          path: |
            ./build
          if-no-files-found: error
      - name: Notify job failure
        if: github.ref == 'refs/heads/master' && failure()
        run: cat $GITHUB_EVENT_PATH | bin/trigger-workflow-message.js build-aborted

  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build_output
          path: ./build/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
      - name: Docker build and push
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - name: Generate dev nais variables
        run: |
          cat > .nais/dev-vars.yaml <<EOF
          ingresses:
            - https://fyllut.dev.nav.no
          image: $IMAGE
          dekorator-host: dekoratoren.dev.nav.no
          dekorator-url: https://dekoratoren.dev.nav.no
          EOF
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config.yaml
          VARS: .nais/dev-vars.yaml
      - name: Generate prod nais variables
        run: |
          cat > .nais/prod-vars.yaml <<EOF
          ingresses:
            - https://nav.no/fyllut
          image: $IMAGE
          dekorator-host: www.nav.no
          dekorator-url: https://www.nav.no/dekoratoren
          EOF
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: prod-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config.yaml
          VARS: .nais/prod-vars.yaml
      - name: Install deps for notification script
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Notify job success
        if: ${{ success() }}
        run: cat $GITHUB_EVENT_PATH | bin/trigger-workflow-message.js skjemautfyller-deployed
      - name: Notify job failure
        if: ${{ failure() }}
        run: cat $GITHUB_EVENT_PATH | bin/trigger-workflow-message.js build-aborted
