name: Continous integration | deployment
on: push

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/skjemautfylling:${{ github.sha }}
  PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
  PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
  PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
  PUSHER_APP_CLUSTER: ${{ secrets.PUSHER_APP_CLUSTER }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Notify job failure
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && failure()
        run: cat $GITHUB_EVENT_PATH | bin/trigger-build-aborted.js

  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Docker build and push
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - name: Generate nais variables
        run: |
          cat > .nais/vars.yaml <<EOF
          ingresses:
            - https://skjema.dev.nav.no
          image: $IMAGE
          EOF
      - uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config.yaml
          VARS: .nais/vars.yaml
      - name: Notify job success
        if: ${{ success() }}
        run: cat $GITHUB_EVENT_PATH | bin/trigger-deployment-success.js
      - name: Notify job failure
        if: ${{ failure() }}
        run: cat $GITHUB_EVENT_PATH | bin/trigger-build-aborted.js
