name: Cypress Tests

on: push
env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress-install:
    runs-on: ubuntu-latest-8-cores
    permissions:
      contents: 'read'
      packages: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.8.0'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
          cache: 'yarn'
      - name: 'Install dependencies'
        run: yarn --frozen-lockfile
      - name: 'Build application'
        run: yarn build
      - name: Upload build arifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            packages/bygger/dist
            packages/bygger-backend/dist
            packages/fyllut/dist
            packages/fyllut-backend/dist
            packages/shared-components/dist
            packages/shared-domain/dist

  cypress-run-fyllut:
    runs-on: ubuntu-latest-8-cores
    needs: cypress-install
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4]
    permissions:
      contents: 'read'
      packages: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.8.0'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
          cache: 'yarn'
      - name: 'Install dependencies'
        run: yarn --frozen-lockfile
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: packages
      - name: Display structure of downloaded files
        run: ls -R
      - name: 'Run mock server'
        run: yarn mocks:fyllut:no-cli &
      - name: 'Cypress tests (fyllut)'
        uses: cypress-io/github-action@v6
        with:
          install: false
          parallel: true
          start: yarn preview:fyllut
          wait-on: 'http://localhost:3001/fyllut/internal/isready'
          wait-on-timeout: 120
          command: yarn cypress:fyllut
          config: video=false
        env:
          FYLLUT_BACKEND_LOGLEVEL: ${{ runner.debug == '1' && 'debug' || 'error' }}

  cypress-run-bygger:
    runs-on: ubuntu-latest-8-cores
    needs: cypress-install
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2]
    permissions:
      contents: 'read'
      packages: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.8.0'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
          cache: 'yarn'
      - name: 'Install dependencies'
        run: yarn --frozen-lockfile
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: packages
      - name: Display structure of downloaded files
        run: ls -R
      - name: 'Cypress tests (bygger)'
        uses: cypress-io/github-action@v6
        with:
          install: false
          parallel: true
          start: yarn preview:bygger
          wait-on: 'http://localhost:3000/internal/isready'
          wait-on-timeout: 120
          command: yarn cypress:bygger
          config: video=false
          config-file: cypress.config.ts
