name: "Build and deploy skjemabygging-formio"
on:
  push:
    branches:
      - "master"
      - "nais-deploy"
env:
  "IMAGE": "docker.pkg.github.com/${{ github.repository }}/skjemabygging-formio:${{\
    \ github.sha }}"
jobs:
  build:
    env:
      CI: true
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/cache@v2"
        with:
          "path": "~/.npm"
          "key": "${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}"
          "restore-keys": "${{ runner.os }}-node-"
      - uses: "actions/setup-node@v1"
        with:
          node-version: '14'
      - name: Cache local node modules
        id: cache-local-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install deps if needed
        if: steps.cache-local-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: "run tests"
        run: "npm test"
      - name: Test library build
        run: npm run prepare
      - name: "compile"
        run: "npm run build"
        env:
          REACT_APP_FORMIO_PROJECT_URL: "https://protected-island-44773.herokuapp.com"
          REACT_APP_PUSHER_CLUSTER: "mt1"
          REACT_APP_PUSHER_KEY: "${{ secrets.REACT_APP_PUSHER_KEY }}"

      - name: "Build and publish Docker image"
        run: "docker build --pull --tag ${IMAGE} . && echo $GITHUB_TOKEN | docker login\
        \ --username $GITHUB_REPOSITORY --password-stdin https://docker.pkg.github.com\
        \ && docker push ${IMAGE}"
        env:
          "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
  deployToDev:
    name: "Deploy to dev"
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: Generate dev nais variables
        run: |
          cat > .nais/dev-vars.yaml <<EOF
          ingresses:
            - https://skjemabygging-formio.dev.intern.nav.no
          image: $IMAGE
          githubGitRef: "master"
          EOF
      - name: "Deploy to dev-gcp"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: "dev-gcp"
          RESOURCE: .nais/nais.yaml
          VARS: .nais/dev-vars.yaml
#  deployToProd:
#    name: "Deploy to prod"
#    needs: "deployToDev"
#    runs-on: "ubuntu-latest"
#    steps:
#    - uses: "actions/checkout@v2"
#    - name: Generate prod nais variables
#        run: |
#          cat > .nais/prod-vars.yaml <<EOF
#          ingresses:
#            - "https://skjemabygging-formio.intern.nav.no"
#          image: $IMAGE
#          githubGitRef: "master"
#          EOF
#    - name: "Deploy to prod-gcp"
#      uses: "nais/deploy/actions/deploy@v1"
#      env:
#        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
#        "CLUSTER": "prod-gcp"
#        "RESOURCE": ".nais/nais.yaml"
#        "VARS": ".nais/prod-vars.yaml"