name: Publish skjemabygger
on:
  workflow_dispatch:
    inputs:
      skjemapubliseringBranch:
        description: "Bransjen på skjemapublisering som oppdateres"
        required: true
        default: "publish-testing"
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
  findAuthor:
    env:
      eventsUrl: https://api.github.com/users/${{ github.event.sender.login }}/events
    runs-on: ubuntu-latest
    outputs:
      author: ${{ steps.findAuthor.outputs.author }}
    steps:
      - name: Show events url
        run: echo $eventsUrl
      - name: Curl events
        run: curl $eventsUrl | jq '.[] | select(.payload.commits?)'
      - id: tryOutputs
        run: echo "::set-output name=flesk::$(curl $eventsUrl | jq '.[] | select(.payload.commits?)')"
      - name: See outputs
        run: echo ${{ steps.tryOutputs.outputs.flesk }}
#      - id: findAuthor
#        run: echo "::set-output name=author::$( curl $eventsUrl | jq '[.[] | select(.payload.commits?) | {author: .payload.commits[].author }] | .[0]')"

  publishBygger:
    runs-on: ubuntu-latest
    env:
      NEW_SKJEMABYGGING_URL: github:navikt/skjemabygging-formio.git#${{ github.sha }}
    steps:
      - name: Show event information
        run: cat $GITHUB_EVENT_PATH | jq .
      - name: Show it from context
        run: echo ${{ github.event }}
      - name: Checkout skjemapublisering
        uses: actions/checkout@v2
        with:
          repository: navikt/skjemapublisering
          ref: ${{ github.event.inputs.skjemapubliseringsBranch }}
          fetch-depth: 0
      - name: Vis original package.json
        run: cat package.json
      - name: Oppdater skjemabygging-formio dependency til ${{ env.NEW_SKJEMABYGGING_URL }}
        run: jq --arg dependencyUrl $NEW_SKJEMABYGGING_URL '.dependencies["skjemabygging-formio"]=$dependencyUrl' package.json > tmp.json
      - name: Swap
        run: |
          rm package.json
          mv tmp.json package.json
      - name: Vis redigert package json
        run: cat package.json
      - name: Check package.json and generate package-lock.json
        run: npm install
      - name: Commit files
        env:
          author: Syver Enstad
          email: syver.enstad@gmail.com
        run: |
          git config --local user.name $author
          git config --local user.email $email
          git add package*.json
          git commit -m "Bump skjemabygging-formio dependency to $NEW_SKJEMABYGGING_URL"
      - name: Push endringen til skjemapublisering
        run: echo Ikke implementert ennå

