name: Publish skjemabygger
on:
  workflow_dispatch:
    inputs:
      skjemapubliseringBranch:
        description: "Bransjen på skjemapublisering som oppdateres"
        required: true
        default: "publish-testing"
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
  publishBygger:
    runs-on: ubuntu-latest
    env:
      NEW_SKJEMABYGGING_URL: github:navikt/skjemabygging-formio.git#${{ github.sha }}
    steps:
      - name: Checkout skjemapublisering
        uses: actions/checkout@v2
        with:
          repository: navikt/skjemapublisering
          ref: ${{ github.event.inputs.skjemapubliseringsBranch }}
          fetch-depth: 0
      - name: Vis original package.json
        run: cat package.json
      - name: Oppdater skjemabygging-formio dependency til ${{ env.NEW_SKJEMABYGGING_URL }}
        run: jq --arg dependencyUrl $NEW_SKJEMABYGGING_URL '.dependencies["skjemabygging-formio"]=$dependencyUrl' package.json > tmp.json
      - name: Swap
        run: |
          rm package.json
          mv tmp.json package.json
      - name: Vis redigert package json
        run: cat package.json
      - name: Check package.json and generate package-lock.json
        run: npm install
      - name: Commit files
        run: |
          git add package*.json
          git commit -m "Bump skjemabygging-formio dependency to $NEW_SKJEMABYGGING_URL"
      - name: Push endringen til skjemapublisering
        run: echo Ikke implementert ennå

