name: Trigger deploy fyllut as app installation
on:
  workflow_dispatch:

  trigger-deploy-fyllut-to-dev:
    name: "Trigger deploy fyllut to dev"
    runs-on: ubuntu-latest
    steps:
      - name: "Generate app installation access token"
        uses: navikt/github-app-token-generator@v1
        id: generate-token
        with:
          private-key: ${{ secrets.PUBLISHING_APP_PRIVATE_KEY }}
          app-id: ${{ secrets.PUBLISHING_APP_ID }}
          repo: navikt/skjemautfylling-formio
      - name: "Trigger deploy fyllut to dev"
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Trigger dev deploy"
          repo: navikt/skjemautfylling-formio
          ref: "dev-deploy"
          token: ${{ steps.generate-token.outputs.token }}
          inputs: '{ "monorepoGitHash": "${{ github.sha }}" }'